### ISSUE TITLE
Crash when I click Poisson Button

### ISSUE THREAD

**Issue by segatecm** [colmap/colmap#2363] opened 2024-01-25 13:25 UTC
I use Dense reconstruction ,  when i finish Fusion and click Poisson, It report:
 [ERROR] Failed to open file: PR_a06736

**To Reproduce**
1. create new project and Start reconstruction
2. open Dense reconstruction dialog
3. Click Undistortion, Stereo, Fusion, Poisson
4. [ERROR] Failed to open file: PR_a06736 and crash

**Expected behavior**
If use Delaunay it work fine.

**Environment:**
 - OS:  Windows 10
 - COLMAP Version 3.9.1
 - iphoneX

**Comment by sarlinpe** [comment] 2024-02-05 14:54
The version of poisson reconstruction that we use supports writing temporary buffers to the current directory only. This bug has been fixed upstream so we should update our copy to the latest version https://github.com/mkazhdan/PoissonRecon You're welcome to help on this.

**Comment by pavel-rodionov** [comment] 2024-03-13 07:32
I believe it would be much easier to fix this when https://github.com/mkazhdan/PoissonRecon/pull/231 will be merged. In that can PoissonRecon should be imported as submodule instead of current approach with a local copy.

**Comment by thunders82** [comment] 2024-06-04 16:49
> The version of poisson reconstruction that we use supports writing temporary buffers to the current directory only. This bug has been fixed upstream so we should update our copy to the latest version https://github.com/mkazhdan/PoissonRecon You're welcome to help on this.

Hi @sarlinpe,
Could you point me to the commit you are mentioning? 
Thank you

**Comment by sarlinpe** [comment] 2024-06-04 21:16
https://github.com/mkazhdan/PoissonRecon/commit/31341bedc0beec0f2079f89d1688b60bfda8f213 adds an option to specify the path to the temporary directory to which the buffer are written (this is a new feature and not a bugfix, contrary to what I had written).

**Closed** 2024-08-06 09:57 UTC
Labels: bug, help wanted
