### ISSUE TITLE
Build error with VS 2013 X64

### ISSUE THREAD

**Issue by json87** [colmap/colmap#29] opened 2016-09-18 00:50 UTC
Hi, thanks for release this wonderful tools. Recently, I have pull down the latest source code and build it with VS 2013 X64. However, some errors occur as following:

patch_match_cuda.cu
1>  
1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5658): error C2015: too many characters in constant
1>  
1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5658): error C2146: syntax error : missing ')' before identifier 'q'
1>  
1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5658): error C2001: newline in constant
1>  
1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5671): error C2143: syntax error : missing ';' before '{'
1>  
1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\concrt.h(5671): error C2143: syntax error : missing ')' before ';'

**Comment by ahojnnes** [comment] 2016-09-18 05:52
Hi,

What CUDA version do you use?

Cheers,
Johannes

**Comment by json87** [comment] 2016-09-18 06:12
Hi, 

The CUDA version is NVIDIA GeForce GTX 770

I think maybe it is not the CUDA version difference causes the problem because I have sccessfully build source code of version 1.1.  These build errors come from source file patch_match_cuda.cu.

I hope these information would be help!

**Comment by ahojnnes** [comment] 2016-09-18 07:49
> The CUDA version is NVIDIA GeForce GTX 770

That is not the CUDA version, that is your graphics card. Do you use CUDA 6 or 7 or 8?

**Comment by json87** [comment] 2016-09-18 08:03
I am sorrry. The CUDA version is 7.5

**Comment by junghyuncho** [comment] 2016-09-22 14:58
I think the problem is caused by the inclusion of the "util/threading.h" in patch_match.h.
So, we can avoid the problem by not nvcc-compiling PatchMatchController class.
For example,  
#ifndef __CUDACC__
#include "util/threading.h"
#endif 
...
#ifndef __CUDACC__
class PatchMatchController : public Thread {
...
}
#endif

**Comment by ahojnnes** [comment] 2016-09-22 15:02
Thanks, I will try the proposed patch. It's strange that I don't see the problem on my machine, which seems to have the exact same compiler versions...

**Comment by ahojnnes** [comment] 2016-09-28 11:08
Thanks for the bug fix! It is now fixed in the master branch.

**Closed by ahojnnes** 2016-09-28 11:08 UTC
