### ISSUE TITLE
Grab image - picture is taken together with the save menu

### ISSUE THREAD

**Issue by andrejpan** [colmap/colmap#44] opened 2016-10-31 10:39 UTC
If I want to take full screen picture on a single monitor, there will be also save menu like on this [picture](https://postimg.org/image/ptk5q65qj/).

**Comment by ahojnnes** [comment] 2016-10-31 12:22
Hm, I am surprised by this, since the grab image functionality just takes a snapshot of the OpenGL widget, which has nothing to do with the "save" dialog window. I cannot reproduce this issue on my machine. What Ubuntu/Qt version are you using?

**Comment by andrejpan** [comment] 2016-10-31 12:53
I am using Ubuntu 14.04 and I guess for Qt version one of these numbers should be enough?
```
pangerca@lapcremers29:/work/pangerca$ qmake --version
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
pangerca@lapcremers29:/work/pangerca$ pkg-config --modversion QtCore
4.8.6
```

**Comment by ahojnnes** [comment] 2016-12-12 08:50
@andrejpan Thanks and sorry for the late reply. I can confirm this issue but it seems to be a bug in Qt and/or the Ubuntu desktop environment. There is not much I can do here at the moment. By the way, I don't see this issue under Ubuntu 16.04. Closing this issue for now, as I cannot resolve it on COLMAP's side.

**Closed by ahojnnes** 2016-12-12 08:50 UTC
