### ISSUE TITLE
Dense mapper problem

### ISSUE THREAD

**Issue by alexsmartens** [colmap/colmap#107] opened 2017-04-15 01:02 UTC
Hey,

I have  a problem with dense mapper. Here is my log: 

```
alex@alex-Alienware-Aurora-R6:~/Downloads/libraries/colmap/build$ ./src/exe/dense_mapper \
>     --workspace_path /media/alex/...my_path../dense \
>     --workspace_format COLMAP \
>     --DenseMapperOptions.max_image_size 0 \
>     --DenseMapperOptions.patch_match_filter true \
>     --DenseMapperOptions.patch_match_geom_consistency true
Reading model...
Reading configuration...
Reading inputs...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1492212490 (unix time) try "date -d @1492212490" if you are using GNU date ***
PC: @     0x7fb2a9ddf428 gsignal
*** SIGABRT (@0x3e800001fbe) received by PID 8126 (TID 0x7fb2a550e700) from PID 8126; stack trace: ***
    @     0x7fb2abf55390 (unknown)
    @     0x7fb2a9ddf428 gsignal
    @     0x7fb2a9de102a abort
    @     0x7fb2aa72184d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fb2aa71f6b6 (unknown)
    @     0x7fb2aa71f701 std::terminate()
    @     0x7fb2aa74ad38 (unknown)
    @     0x7fb2abf4b6ba start_thread
    @     0x7fb2a9eb082d clone
    @                0x0 (unknown)
Aborted (core dumped)
```
What do you think Johannes ?

**Comment by Vaquero84** [comment] 2017-05-09 05:21
On windows 10, the GUI application just terminates when attempting the dense reconstruction (also auto reconstruct) somewhere after "reading inputs" in the stereo step. It might be related to this issue, but I can't be sure, because it just closes and it's too fast to have a look at the log. Is the log saved automatically somewhere, so I can have a look at it?

**Comment by ahojnnes** [comment] 2017-05-09 14:13
Can you run the `dense_stereo` binary from the command-line? If you downloaded the pre-built binaries from the website, you can find them in the `bin` directory.

**Comment by alexsmartens** [comment] 2017-05-09 15:29
1. I also have the same problem with the windows 10 GIU dense reconstruction.

2.  The same problem during automatic reconstruction with the latest version of Colmap binaries (Ubuntu 16.04):
```
Reading model...
Reading configuration...
Reading inputs...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1494293862 (unix time) try "date -d @1494293862" if you are using GNU date ***
PC: @     0x7fc569523428 gsignal
*** SIGABRT (@0x3e8000055f8) received by PID 22008 (TID 0x7fc52f7fe700) from PID 22008; stack trace: ***
    @     0x7fc56e29f390 (unknown)
    @     0x7fc569523428 gsignal
    @     0x7fc56952502a abort
    @     0x7fc569e6584d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fc569e636b6 (unknown)
    @     0x7fc569e63701 std::terminate()
    @     0x7fc569e8ed38 (unknown)
    @     0x7fc56e2956ba start_thread
    @     0x7fc5695f482d clone
    @                0x0 (unknown)
Aborted (core dumped)
```

3. My attempt to run `dense_stereo` faced the following problem (Ubuntu 16.04):
```
$ ./src/exe/dense_stereo \
>     --workspace_path /media/alex/...my_path../dense \
>     --workspace_format COLMAP \
>     --DenseStereo.max_image_size 0 \
>     --DenseStereo.filter false \
>     --DenseStereo.geom_consistency false \
>     --DenseStereo.num_iterations 4
Reading model...
F0509 09:25:00.597965  3147 reconstruction.cc:1591] Check failed: file.is_open() 
*** Check failure stack trace: ***
    @     0x7f83c492a5cd  google::LogMessage::Fail()
    @     0x7f83c492c433  google::LogMessage::SendToLog()
    @     0x7f83c492a15b  google::LogMessage::Flush()
    @     0x7f83c492ce1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x61fee6  colmap::Reconstruction::ReadCameras()
    @           0x6231ab  colmap::Reconstruction::Read()
    @           0x5ffd47  colmap::mvs::Model::ReadFromCOLMAP()
    @           0x601a0b  colmap::mvs::Model::Read()
    @           0x567448  colmap::mvs::(anonymous namespace)::ReadPatchMatchProblems()
    @           0x56ab45  colmap::mvs::PatchMatchController::Run()
    @           0x6746dc  colmap::Thread::RunFunc()
    @     0x7f83bfdbfc80  (unknown)
    @     0x7f83c41c66ba  start_thread
    @     0x7f83bf52582d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
```

**Comment by alexsmartens** [comment] 2017-05-16 16:06
Hi,
is there any possibility this issue is solvable?

**Comment by ahojnnes** [comment] 2017-05-16 17:09
I am on vacation and will get back to you in a week.

**Comment by alexsmartens** [comment] 2017-05-16 17:17
Sounds good,
have a great time!

**Comment by LenaSailor** [comment] 2017-05-21 15:44
Hi fellow Colmap 'activists'.

Similar to some other contributors I'm having a problem running **dense_stereo**  in colmap under Win10.    I'm using a GTX970 and have eliminated all timeout issues.  Problem exists whether using the GUI or 
 command line.

Typical log instances here:

**F0519 21:50:29.863973 12236 image.cc:41] Check failed: width_ == bitmap_.Width() (3009 vs. 2999)
*** Check failure stack trace: ***

F0519 23:31:33.841164  6464 image.cc:41] Check failed: width_ == bitmap_.Width() (2998 vs. 2999)
*** Check failure stack trace: *****

Help would be much appreciated at your convenience (holidays are no excuse!).

**Comment by ahojnnes** [comment] 2017-05-21 16:52
Is it possible for you to share your dense workspace folder?

**Comment by LenaSailor** [comment] 2017-05-21 17:12
Hi and thanks for your very prompt response.

 

I would be happy to share the folder except that its empty!  It gets as far as being created but generally crashes out at the PatchMatch 'Read input' (or something similar) stage.

**Comment by ahojnnes** [comment] 2017-05-21 17:25
Can you share the sparse reconstruction and the images?

**Comment by LenaSailor** [comment] 2017-05-21 18:05
Hi again.

 

You can see the sparse folder and (some of the) images here <http://aerial-photoco.uk/SFM/> .  There are 34 in the complete set.  Hope this helps.

**Comment by ahojnnes** [comment] 2017-05-21 19:15
The image folder is incomplete. Not all images in the sparse reconstruction are present in the images folder. Are you sure you uploaded everything?

**Comment by LenaSailor** [comment] 2017-05-21 19:39
Hi

 

Only the uploaded image folder was incomplete.  The actual image folder was complete at the time of processing however.

 

For the sake of completeness I've now uploaded all images.

**Comment by ahojnnes** [comment] 2017-05-21 20:54
I don't know what you are exactly doing here, but it works fine for me using the following commands:
```
./src/exe/image_undistorter --image_path ~/data/aerial/images --input_path ~/data/aerial/sparse/0 --output_path ~/data/aerial/dense
./src/exe/dense_stereo --workspace_path ~/data/aerial/dense  --workspace_format COLMAP
```

I suspect you mixed up the undistorted and distorted sparse reconstruction and/or images.

**Comment by LenaSailor** [comment] 2017-05-21 22:09
Thanks again for your patience.  I'm going to rerun tomorrow and update the server files.  The batch file I'm running is this:

 

set projpath=y:\colmap

set imagepath=y:\colmap\images

set dbpath=y:\colmap\bin\1999.db

 

cd /D %projpath%\bin

 

database_creator --project_path %projpath% --database_path %dbpath%

 

feature_extractor --database_path %dbpath% --image_path %imagepath%

exhaustive_matcher --database_path %dbpath%

 

md %projpath%\sparse

 

mapper --database_path %dbpath% --image_path %imagepath% --export_path %projpath%\sparse

 

md %projpath%\dense

 

image_undistorter --image_path %imagepath% --input_path %projpath%\sparse\0 --output_path %projpath%\dense 

 

dense_stereo --workspace_path %projpath%\dense --workspace_format COLMAP

**Comment by LenaSailor** [comment] 2017-05-21 22:24
Just done a quick check and got this after a successful undistort

 

y:\Colmap\bin>dense_stereo --workspace_path y:\colmap\dense --workspace_format COLMAP

Reading workspace...

Reading configuration...

 

==============================================================================

Processing view 1 / 34

==============================================================================

 

Reading inputs...

 

PatchMatch::Problem

-------------------

ref_image_id: 0

src_image_ids: 1 3 4 5 6 7 8 9 19 30 31 32 33

 

PatchMatch::Options

-------------------

gpu_index: 0

depth_min: 2.70155

depth_max: 9.18533

window_radius: 5

sigma_spatial: 5

sigma_color: 0.2

num_samples: 15

ncc_sigma: 0.6

min_triangulation_angle: 1

incident_angle_sigma: 0.9

num_iterations: 5

geom_consistency: 0

geom_consistency_regularizer: 0.3

geom_consistency_max_cost: 3

filter: 1

filter_min_ncc: 0.1

filter_min_triangulation_angle: 3

filter_min_num_consistent: 2

filter_geom_consistency_max_cost: 1

 

PatchMatch::Run

---------------

Initialization: 0.6474s

cudaCheckError() with sync failed at C:/Users/jschoenb/Development/colmap/src/mvs/patch_match_cuda.cu:1327 : unknown error

**Comment by LenaSailor** [comment] 2017-05-21 23:58
Workspace folders updated here <http://aerial-photoco.uk/SFM/>  from most recent crash.

**Comment by ahojnnes** [comment] 2017-05-22 01:17
Please refer to https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction to fix this issue under Windows. 

Best,
Johannes

**Comment by LenaSailor** [comment] 2017-05-22 11:53
Hi.  Yes, this is where I started but I went down the Microsoft route first as the NVidia link doesn't work.  I added the recommended registry entry for TDR but without success. Having located the appropriate NVidia 'NSight' utility option and set the TDR delay to 60 Seconds - crash problem over!   As a matter of interest the complete pipeline took nearly 3 hours for the 34 images on an Intel 4-core i7 3.4GHz processor 16Gb RAM with a GTX970 GPU (running flat out much of the time).  Is this about what I should expect in terms of performance?  

 

Anyway, many thanks for your support and I look forward to continuing tests with some different datasets.

 

Best regards

 

Stuart

**Comment by ahojnnes** [comment] 2017-05-22 11:58
This sounds right, since your GPU is not too powerful (relatively ;-)) and you are computing depth at full resolution, which might be overkill. I suggest to set e.g. --max_image_size 2000 to speedup the processing.

**Comment by LenaSailor** [comment] 2017-05-22 12:20
OK thanks.  I'll give it a whirl.

 

Stuart

**Comment by Vaquero84** [comment] 2017-05-23 12:51
I was able to reconstruct a mesh in one project by manually going through the steps involved, after setting HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDrivers TdrDelay to 60 (DWord, decimal). But in other projects the **automated reconstruction** using the GUI still crashes and terminates the GUI. I get the error:
_out of memory in C:/Users/jschoenb/Development/colmap/src/.\mvs/gpu_mat.h at line 151
QObject::~QObject: Timers cannot be stopped from another thread_
What to do about it?
With the manual steps I set max_image_size to 750.

Sometimes I also still get the _Check failed: width_ == bitmap_.Width() (4327 vs. 4326)
*** Check failure stack trace: ***_ kind of crash when attempting the dense reconstruction, but it's not clear to me what's causing it.

**Comment by LenaSailor** [comment] 2017-05-23 15:07
Hi.  Yes it's very frustrating and I followed the advice about TDRdelay (a la Microsoft)  but with no luck at all. Turns out that if you have a recent (possibly any!) NVidia card then you have to use the NVidia utility 'NSight Monitor'  (I believe it came with the NVidia diver).  Problem over for me.  Let me know how you get on.

 

Regards

 

Stuart

**Comment by KimRoos** [comment] 2017-05-25 18:37
I can not get the stereo function to work on the dev och 3.0 version, but for some reason it works great on the 2.1 version. I am using Windows 10.

**Comment by ahojnnes** [comment] 2017-05-25 18:42
What error do you see?

**Comment by KimRoos** [comment] 2017-05-25 18:55
I am using the GUI and it it loads the next image and then it writes:

 PatchMatch::Run
--------------------

After that the hole program crashes after 2-3 minutes.

**Comment by ahojnnes** [comment] 2017-05-25 19:04
@KimRoos Sounds like you are experiencing this issue here: https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction - did you increase the timeout?

**Comment by KimRoos** [comment] 2017-05-25 19:22
I am now using 1000 for the WDDM TDR Delay, is it too small?

I started this time the program from the dos prompt and got the following error:

D:\COLMAP-dev-windows\bin>colmap
Initialization: 2.3675s
 Sweep 1: 13.5357s
 Sweep 2: 7.5539s
 Sweep 3: 9.2318s
 Sweep 4: 7.1307s
Iteration 1: 37.4539s
 Sweep 1: 8.3213s
 Sweep 2: 7.1348s
 Sweep 3: 8.2788s
 Sweep 4: 7.1922s
Iteration 2: 30.9288s
 Sweep 1: 8.2902s
 Sweep 2: 7.2479s
 Sweep 3: 8.2074s
 Sweep 4: 7.1432s
Iteration 3: 30.8904s
 Sweep 1: 8.2308s
 Sweep 2: 6.9007s
 Sweep 3: 8.2551s
 Sweep 4: 7.3889s
Iteration 4: 30.7773s
 Sweep 1: 8.2543s
 Sweep 2: 7.2512s
 Sweep 3: 8.2099s
out of memory in C:/Users/jschoenb/Development/colmap/src/.\mvs/gpu_mat.h at line 151
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by ahojnnes** [comment] 2017-05-26 15:46
@KimRoos The error says "out of memory". Please refer to https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction for info on how to solve this issue.

**Comment by ahojnnes** [comment] 2017-05-26 15:51
@ everyone in this thread:

 - The latest commits on the "dev" branch changed the behavior of the dense stereo module. It should be easier to compute geometric stereo results now. Everything is computed in a single pass of calling ``dense_stereo --DenseStereo.geom_consistency true``. Please refer to the ``run-colmap-photometric.sh`` and ``run-colmap-geometric.sh`` scripts produced by the latest ``image_undistorter`` for example usage.
 - The errors ``Check failed: width == bitmap_.Width()`` some of you encounter are caused by running the ``automatic_reconstructor`` twice on the same workspace folder. Please clear your workspace folders once and re-run. This won't happen in the future with the latest commits in the "dev" branch.

Thanks for all the feedback and let me know whether this works for you.

**Comment by ahojnnes** [comment] 2017-05-26 17:09
Sorry, but it appears there is another small bug that I'll fix over the weekend. I'll let you know once it is committed.

**Comment by ahojnnes** [comment] 2017-05-29 17:28
The errors should be fixed now and the memory usage even lower. In addition to the previously described changes, you can now also set ``DenseFusion.max_image_size``, which down-samples your images, depth maps, normal maps for fusion. This works even if you computed them in higher resolution. No need to recompute them. Moreover, there is a new "medium" quality mode in the automatic reconstructor. Let me know how this works for you. If I get positive feedback, I will push a 3.1 version soon.

**Comment by alexsmartens** [comment] 2017-05-29 17:45
Sounds very good, 
will test the updated version and get back to you with the feetback soon

**Comment by LenaSailor** [comment] 2017-05-29 22:15
Hi

 

Looks interesting but I'm going to be away for a week or so. I'll give it a shot when I get back.

 

Best regards

 

Stuart

**Comment by KimRoos** [comment] 2017-05-30 16:19
With down sampling the image from max_image_size 2000 to 1500 it works great for me, without down sampling I get the same out of memory error as earlier.

**Comment by alexsmartens** [comment] 2017-05-30 23:00
I am working with the updated version of the master brunch. 
Installation again takes hours (Ubuntu 16.04) ..

Testing `dense_stereo` on the data obtained by the previous version of Colmap (sparse model, etc.)   still gives the similar error

```
./src/exe/dense_stereo \
>     --workspace_path /media/alex/...my_path../dense \
>     --workspace_format COLMAP \
>     --DenseStereo.max_image_size 0 \
>     --DenseStereo.geom_consistency true
Reading workspace...
F0530 16:52:56.841083  4589 reconstruction.cc:1591] Check failed: file.is_open() /media/alex/...my_path../dense/sparse/cameras.txt
*** Check failure stack trace: ***
    @     0x7fbec3df35cd  google::LogMessage::Fail()
    @     0x7fbec3df5433  google::LogMessage::SendToLog()
    @     0x7fbec3df315b  google::LogMessage::Flush()
    @     0x7fbec3df5e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x628928  colmap::Reconstruction::ReadCameras()
    @           0x62bc1b  colmap::Reconstruction::Read()
    @           0x56e517  colmap::mvs::Model::ReadFromCOLMAP()
    @           0x57001b  colmap::mvs::Model::Read()
    @           0x569050  colmap::mvs::Workspace::Workspace()
    @           0x57672e  colmap::mvs::PatchMatchController::ReadWorkspace()
    @           0x57b74c  colmap::mvs::PatchMatchController::Run()
    @           0x67f2fc  colmap::Thread::RunFunc()
    @     0x7fbebf478c80  (unknown)
    @     0x7fbec367b6ba  start_thread
    @     0x7fbebebde82d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
```

Any suggestions?

**Comment by ahojnnes** [comment] 2017-05-31 07:38
@alexsmartens If the installation takes hours, then your machine must be really slow or you are compiling on a single thread, etc. The error message is pretty clear, in that it says that the file ``/media/alex/...my_path../dense/sparse/cameras.txt`` could not be opened. Make sure that the file exists and that it has the correct access rights.

**Comment by alexsmartens** [comment] 2017-05-31 20:45
- I seem to have a decent machine Intel 4.2 GHz, Nvidia Titan X, 16 GB RAM. I checked the Nvidia and cuda drivers: 
```
$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.66  Mon May  1 15:29:16 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```
It looks like I have cuda enabled. How can I check if I have multithreading enabled while compiling colmap?

- this error was pretty obvious to me, this is what I checked first that the file exists and it's access rights. Nothing helped, that's why I reported the problem here. Anything else I can try? If there's nothing else to check, I will try to run all the commands again after we clarify the multi-threading issue

**Comment by alexsmartens** [comment] 2017-06-02 04:38
Update:
1) I installed CUDA 8.0 toolkit. The compilation still takes hours. 
Is there anything could be done to compile and run Colmap faster?

There are my CUDA samples output:

```
$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "TITAN X (Pascal)"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 12188 MBytes (12779978752 bytes)
  (28) Multiprocessors, (128) CUDA Cores/MP:     3584 CUDA Cores
  GPU Max Clock rate:                            1531 MHz (1.53 GHz)
  Memory Clock rate:                             5005 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = TITAN X (Pascal)
Result = PASS
```

```

$ ./bandwidthTest
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: TITAN X (Pascal)
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			6355.6

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			6434.7

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)	Bandwidth(MB/s)
   33554432			340479.8

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

```

2) I recalled all the colmap versions installation time till Oct 16, and only the previous version compiled quickly in my case

**Comment by ahojnnes** [comment] 2017-06-02 09:25
Are you compiling in release or relwithdeb mode?

**Comment by alexsmartens** [comment] 2017-06-02 22:00
Sorry, I did not quite get you. What peace of the software are you talking about?
In fact, I usually do not specify `CMAKE_BUILD_TYPE`.

One more answer on the question you asked before, I compile Colmap with multi threads (`make -j`).  


What would you recommend to be the next step?

**Comment by ahojnnes** [comment] 2017-06-03 12:50
I have no idea why your build takes so long. Several hours is definitely too long... maybe you're compiling from a network disk?

**Comment by alexsmartens** [comment] 2017-06-03 17:31
Nope, I'm compiling form a local disk

**Comment by ahojnnes** [comment] 2017-06-03 18:00
I cannot help you with your slow compilation here. I also haven't had anyone else reporting a similar issue. Sure, it is not fast to compile the whole library but several hours on a multi core machine is not normal.

**Comment by alexsmartens** [comment] 2017-06-05 16:08
I report successful run of the reconstruction cycle. 

My photo set: 400 images 3264 x 2448
My PC: Intel 4.2 GHz, Nvidia Titan X, 16 GB RAM
  
My timing:
`feature_extractor` -         0 min
`exhaustive_matcher ` -  52 min
`mapper                 ` -                      37 min
`image_undistorter ` -      0 min  *(max_image_size 2000)
`dense_stereo` -           372 min
`dense_fuser` -             350 min
TOTAL TIME -               811 min (13.5 hr)

Does it sound like reasonable time?

**Comment by ahojnnes** [comment] 2017-06-05 16:17
Sounds reasonable and I am glad you could finally run the pipeline successfully. Fusion could probably be speeded up with more RAM. Thanks for the feedback!

**Comment by ahojnnes** [comment] 2017-06-13 10:20
I assume these issues are solved with the latest version, closing this now. Feel free to reopen. Thanks to everyone for the feedback.

**Closed by ahojnnes** 2017-06-13 10:20 UTC

**Comment by alexsmartens** [comment] 2017-07-18 19:04
Hi @ahojnnes, 
can we reopen this issue, please

I have an analogous issue on a different data set

```
$ ./src/exe/dense_stereo    
 --workspace_path /media/alex/...my_path../dense     
--workspace_format COLMAP     
--DenseStereo.max_image_size 0    
--DenseStereo.geom_consistency true

Reading workspace...
Reading configuration...

...

==============================================================================
Processing view 123 / 263
==============================================================================

Reading inputs...
F0718 12:01:47.104317   915 image.cc:41] Check failed: width_ == bitmap_.Width() (1000 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f3cb74c45cd  google::LogMessage::Fail()
    @     0x7f3cb74c6433  google::LogMessage::SendToLog()
    @     0x7f3cb74c415b  google::LogMessage::Flush()
    @     0x7f3cb74c6e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x56db64  colmap::mvs::Image::SetBitmap()
    @           0x57ab29  colmap::mvs::PatchMatchController::ProcessProblem()
    @           0x57c0fc  std::_Function_handler<>::_M_invoke()
    @           0x57c739  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f3cb6d53a99  __pthread_once_slow
    @           0x57d116  std::call_once<>()
    @           0x57d340  _ZNSt17_Function_handlerIFvvEZN6colmap10ThreadPool7AddTaskIMNS1_3mvs20PatchMatchControllerEFvRKNS4_10PatchMatch7OptionsEmEIPS5_RS7_RmEEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSH_DpOSI_EUlvE_E9_M_invokeERKSt9_Any_data
    @           0x67ff22  colmap::ThreadPool::WorkerFunc()
    @     0x7f3cb2b49c80  (unknown)
    @     0x7f3cb6d4c6ba  start_thread
    @     0x7f3cb22af3dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)



```

**Comment by ahojnnes** [comment] 2017-07-19 10:35
Can you share the data necessary to reproduce this issue?

**Comment by alexsmartens** [comment] 2017-07-22 02:57
Sorry for my late reply, I was out of city for some time. 
Meanwhile, I saw that you made some updates to COLMAP just recently. So, I compiled COLMAP with the last updates and this solved my problem. Thank you

**Comment by alexsmartens** [comment] 2017-07-25 17:05
Hi @ahojnnes ,

I'm reporting that the last updates which solved my recent problem simultaneously increased computational time dramatically (from 36 to 112 min in my case). I got this time difference by running `dense_stereo `. Is there anything can be done about it?

**Comment by ahojnnes** [comment] 2017-07-25 19:06
Can you figure out which commits you are comparing in this case?

**Comment by alexsmartens** [comment] 2017-07-25 23:43
I have an overwhelming amount of work in the next two weeks. Can try to work it out later
So far, I can tell you that the first COLMAP version (FAST) I downloaded and compiled on 31/05/17 and the other version (SLOW) was downloaded and compiled on 24/07/17

**Comment by yonasteo** [comment] 2017-10-06 08:17
Hi @ahojnnes  and @alexsmartens ,
 
I am having the same issue on the latest commit COLMAP 3.2  for images  from two different cameras with similar resolution. could you please tell me what is the reason behind it ?  


==============================================================================
Processing view 1 / 698
==============================================================================

Reading inputs...
F1005 23:33:33.636186   5656 image.cc:41] Check failed: width_ == bitmap_.Width() (1919 vs. 0) 
*** Check failure stack trace: ***

**Comment by ahojnnes** [comment] 2017-10-07 09:24
Are some of the undistorted images in the workspace missing or are you using a non-standard bitmap format?

**Comment by yonasteo** [comment] 2017-10-08 09:37
Hi @ahojnnes 

Thanks for the reply, today I found out that  the undistort step needs all the images to be written with there extension like "Lena.png" . if the pictures dosen't have the extension appended like this "Lena", it will fail to create the undistorted images.

**Comment by ahojnnes** [comment] 2017-10-08 09:51
@yonasteo Thanks for the feedback. This should be fixed with https://github.com/colmap/colmap/commit/4d96c9f089ec19c96564f92771814ccffa504b00 - can you check whether it works for you and let me know? Thanks.

**Comment by yonasteodros** [comment] 2017-10-11 14:19
@ahojnnes Thanks for the fix it works verywell !

**Comment by mattbrown11** [comment] 2019-09-24 00:09
I also ran into this error message when one of my .photometric.bin files had size 0 because of a previous crash.
