### ISSUE TITLE
Unable to generate a dense map by importing SIFT Features from another library

### ISSUE THREAD

**Issue by AsimJalwana** [colmap/colmap#444] opened 2018-07-27 01:43 UTC
**Problem**
I imported the SIFT features by following the online tutorial. The .jpg.txt files were placed in same folder and once I extracted the features and did the matching, I finally created a sparse representation which is great.
The pic shows the sparse model

![sparsemodel](https://user-images.githubusercontent.com/40447398/43296771-f7f77dec-917f-11e8-9dbe-7ce139d18251.png)

However when I tried the dense reconstruction, it gave almost nothing. The fused.ply file is 45kb.

**To Reproduce**
I extracted the SIFT features from https://github.com/pitzer/SiftGPU. The features extraction and matching looks great. I can see number of matches in the database table. Just doing the dense reconstruction afterwards did not produce any result. 

**Expected Problem**
I ran the colmap on the same dataset by extracting the features on GPU and following the rest of the pipeline. The results look great for the dense and sparse reconstruction.

All below results are for the below image
![originalimage](https://user-images.githubusercontent.com/40447398/43297014-5b8bcc04-9181-11e8-8fc6-349a6c892245.png)

For the imported features, the Photometric Depth map and Normal maps are as below
![photometricdepthmap](https://user-images.githubusercontent.com/40447398/43296955-f9cdff0a-9180-11e8-8c0a-12ec595e241b.png)

![photometricnormalmap](https://user-images.githubusercontent.com/40447398/43296958-fc09f90e-9180-11e8-8e17-16ac2a41e593.png)

They look very noisy. The same maps for the same image for the experiment where colmap extracted features it self are below
![photometricdepthmap_original](https://user-images.githubusercontent.com/40447398/43297001-4f001760-9181-11e8-9d28-bc99b8ec963b.png)
![photometricnormalmap_original](https://user-images.githubusercontent.com/40447398/43297004-5032d384-9181-11e8-8a68-e0a7bb9e15ea.png)

Can you please guide if I am missing some important step in the whole pipeline? Sparse construction is fine but why dense reconstruction is failing?

**Comment by AsimJalwana** [comment] 2018-07-27 15:32
I am trying to run another pipe line which is based on the SIFT GPU specific version( as order of feature descriptor changes from implementation to implementation). I was wondering to get a good dense model based on the same features from colmap. Bundler does not generate the dense model as good.

May be features are getting rescaled in colmap which does not happen when features are imported from outside?

**Comment by ahojnnes** [comment] 2018-07-27 21:03
I am literally using the same implementation. As the one you linked, with a few parameter modifications and bug fixes. So, you could just use COLMAP’s feature extractor. Otherwise, there shouldn’t be any feature rescaling involved in COLMAP. Not sure what the issue is. If you get a good sparse reconstruction from your imported features, then there shouldn’t be any reason, that it leads to a bad dense reconstruction. Are the steps you execute really the same? Please list the commands explicitly for both and I can check.

**Comment by AsimJalwana** [comment] 2018-07-28 07:20
I did explore the code and saw that SIFT GPU is from ChangChang Wu.The sparse clouds from Imported features and the colmap generated features are visually similar. 
I did both of the experiments from the GUI, all the parameters were default except for gpu_index which I adjusted to 0 (as I had two GPU in the system and only of them is powerful). This choice was same for both the experiments. I will re-run the experiments from command line and share the commands with you.

**Comment by AsimJalwana** [comment] 2018-07-31 01:54
In the mean time, I am waiting for access to GPU computer in my lab. 

Would it be possible to use your MVS separately using as input another SfM (sparse pointcloud generation)?

**Comment by AsimJalwana** [comment] 2018-08-05 02:46
I found that the https://github.com/pitzer/SiftGPU generates the features such that its x,y,scale, orientation are y,x, scale, orientation for the colmap. Now feeding the features by first transforming them, generated dense point cloud, the photometric and depth maps are not noisy like earlier.

**Comment by ahojnnes** [comment] 2018-08-05 10:32
Okay, glad to hear you resolved the issue. But again, COLMAP uses SiftGPU for feature extraction, so there is no reason to import features manually. Closing this as resolved and please let me know if you have other questions.

**Closed by ahojnnes** 2018-08-05 10:32 UTC
