### ISSUE TITLE
Core dumped error when i run reconstruction > start reconstruction

### ISSUE THREAD

**Issue by pobsteta** [colmap/colmap#119] opened 2017-05-10 10:04 UTC
![capture d ecran de 2017-05-10 11-59-54](https://cloud.githubusercontent.com/assets/932599/25893561/959fac14-3578-11e7-8fbf-d440f5d848ac.png)

When i run make test in ceres-sover all is right, but when i run make test in colmap, #45 bundle_adjustement_test failed ?
Any idea ?

**Comment by pobsteta** [comment] 2017-05-10 10:04
I was on ubuntu 16.04 64 bits

**Comment by ahojnnes** [comment] 2017-05-10 13:57
Are you using the default Eigen version from the Ubuntu repository? This version is known to cause this problem and you can fix it by changing to pretty much any other Eigen 3.2.x or 3.3.x version.

**Comment by pobsteta** [comment] 2017-05-13 09:15
I have the libeigen3-dev 3.3~beta1-2 version, is it ok ?

**Comment by ahojnnes** [comment] 2017-05-13 11:36
Upgrade it downgrade and recompile. That should solve the problem. Let me know if that works.

**Comment by pobsteta** [comment] 2017-05-13 20:14
yes it is ok but now, the dense construction crashed when i use high 
quality ?
@+

**Comment by ahojnnes** [comment] 2017-05-13 23:52
What does it say?

**Comment by pobsteta** [comment] 2017-05-14 07:04
![capture d ecran de 2017-05-14 08-58-28](https://cloud.githubusercontent.com/assets/932599/26031902/5ba7da4a-3884-11e7-8695-83c657f65e18.png)

**Comment by ahojnnes** [comment] 2017-05-14 14:39
This is caused by a Cuda kernel runtime timeout. Checkout the colmap documentation for a solution: https://colmap.github.io/faq.html#fix-gpu-freezes-and-timeouts-during-dense-reconstruction

**Comment by heimsi** [comment] 2017-05-19 09:41
I experienced exactly the same error as @pobsteta had in the first post of this thread. As @ahojnnes said by downgrading to Eigen version 3.2.5, the problem got resolved.

**Comment by ahojnnes** [comment] 2017-05-19 14:10
Thanks for the feedback.

**Comment by ahojnnes** [comment] 2017-05-22 12:03
I will close this issue for now since it seems that this problem is indeed caused by Eigen and not COLMAP. Please reopen if you think otherwise. Thanks everyone for the feedback!

**Closed by ahojnnes** 2017-05-22 12:03 UTC
