### ISSUE TITLE
Panoramic Camera model

### ISSUE THREAD

**Issue by daleydeng** [colmap/colmap#6] opened 2016-05-01 08:05 UTC
I saw the colmap has a lot of camera models, is it easy to add new panoramic model? So the street view image could also be applied~

May be 3D bearing vector (unit vector) is more suitable compared with the 2D feature coordinate in this case.~

**Comment by ahojnnes** [comment] 2016-05-01 08:17
Hi @daleydeng,

For now, it is not straightforward to add non-central camera models, which I assume would be the case for the type of data you mention. There is a chance that I'll release code for it at some point in the future, but it is not clear when.

If this answers your question, I would close the issue for now. Otherwise, feel free to follow up.

Cheers, Johannes

**Comment by daleydeng** [comment] 2016-05-01 15:27
Thanks for reply. Camera rig would be non-central, but panorama is central. Different with conventional rectilinear camera model, there is no front or back (no cherilty check) in the panorama camera and the pixel based mapping function would be large distorted, Maybe bearing vector is better representation for this case.
The reprojection error could be chord distance between two rays~

![image](https://cloud.githubusercontent.com/assets/770506/14942601/740681dc-0f8f-11e6-87ef-344cb1e05477.png)

Check http://laurentkneip.github.io/opengv/page_how_to_use.html#sec_vocabulary for more details~

**Comment by ahojnnes** [comment] 2016-05-01 16:05
Hi,

Thanks for the clarification. This makes sense and should be possible with some modification of the current implementation. XY image coordinates would then simply be your azimuth and elevation angles. One important thing that would have to be adapted are the carefully chosen pixel error thresholds. Let me know if you want to tackle this problem and you have questions. Happy to help.

Best,
Johannes

**Comment by daleydeng** [comment] 2016-05-01 17:00
All right, I will contact you when I tackle this problem~~

**Comment by daleydeng** [comment] 2016-05-10 12:03
I have added support for generic central camera (such as spherical camera) as
https://github.com/daleydeng/colmap/tree/cvai, @ahojnnes could ref it when needed!

**Comment by ahojnnes** [comment] 2016-05-10 12:22
@daleydeng Hi, this looks great. Would you have a test dataset to share to test the functionality? Thanks!

**Comment by daleydeng** [comment] 2016-05-10 13:15
@ahojnnes , Hi, I've added data in there, check it out~, but there is a little bug when running about 160  images, I'm figuring it out~

**Comment by daleydeng** [comment] 2016-05-10 13:20
I saw there is a change in vocab tree, Vocab->retrieval, do you have the new trained tree?

**Comment by ahojnnes** [comment] 2016-05-10 13:45
@daleydeng Uploaded the new trees here: http://people.inf.ethz.ch/jschoenb/colmap/vocabulary-trees/development-version/

**Comment by daleydeng** [comment] 2016-05-10 13:51
Ok~

**Comment by daleydeng** [comment] 2016-05-10 14:24
I think I saw the  problem, refine_focal_length should be disabled in spherical case, change *refine_focal_length to false in proj.ini

**Comment by daleydeng** [comment] 2016-05-10 14:50
@ahojnnes  Check the new result, now we need a sphere entity in gl viewer for each spherical camera~

**Comment by ahojnnes** [comment] 2016-05-10 15:02
@daleydeng The results look much better now! Would you be willing to prepare a pull request against the current master branch? I am happy to incorporate your changes.

**Comment by ahojnnes** [comment] 2016-05-10 15:04
For my understanding, did you do normal feature extraction or how did you translate from x,y to spherical coordinates?

**Comment by daleydeng** [comment] 2016-05-10 15:40
the Spherical camera itself defines how the world coordinate(Vector3d, u, v, w) to the image coordinate(Vector2d, x, y)

normalization has been done in camera it self. by caluclating the panning and tilting angle from pixel

There is no change in feature extraction, they are just orignal 2D feature image coordinate

template <typename T>
void SphericalCentralCameraModel::WorldToImage(const T* params, T u,
                                               T v, T w, T* x, T* y) {
  const T f = params[0];
  const T c1 = params[1];
  const T c2 = params[2];

  T l = ceres::sqrt(u * u + v * v + w * w);
  u = u/l, v = v/l, w = w/l;
  T p = ceres::atan2(u, w), t = -ceres::asin(v);

  *x = p*f+ c1;
  *y = -t*f + c2;
}

template <typename T>
void SphericalCentralCameraModel::ImageToWorld(const T* params, const T x,
                                               const T y, T* u, T* v, T *w) {
  const T f = params[0];
  const T c1 = params[1];
  const T c2 = params[2];

  auto p = (x - c1) / f, t = -(y - c2) / f;
  auto cos_t = ceres::cos(t);
  *u = cos_t * ceres::sin(p);
  *v = -ceres::sin(t);
  *w = cos_t * ceres::cos(p);
}

**Comment by daleydeng** [comment] 2016-05-10 16:10
OK, let me cleanup my code for some name conventions and something for pull request, and after that, Cylindrical Camera could also be added~

**Comment by ahojnnes** [comment] 2016-05-10 16:56
I could host it on my Google Drive folder, if you give me the permission?

**Comment by daleydeng** [comment] 2016-05-10 17:02
Absolutely, then I delete it from my repo~

**Comment by ahojnnes** [comment] 2016-05-10 17:27
I'll wait with uploading the data until we have the spherical model merged. Cylindrical model also sounds interesting. Do you have suitable data to test?

**Comment by daleydeng** [comment] 2016-05-11 04:02
The panorama image is taken by theta S 
![image](https://cloud.githubusercontent.com/assets/770506/15169609/97c85ff4-176f-11e6-86b0-edd80bcbd72c.png)
There does exist cylindrical camera 
![image](https://cloud.githubusercontent.com/assets/770506/15169617/a9a60e56-176f-11e6-8cba-9c231bf8834f.png)
and I have the device.

By the way, I'm restructoring my code, I saw there exist a lot "const" in the source code, In my opinion
for function arguments, 
fn((const double)x) is equal to fn((double)x), const is necessary.
for large structure S
fn(const S) is less efficient than fn(const &S) without extra copy,  maybe you mean const & instead of const.  Also mentioned as google C++ coding style~~

 Remove the necessary const will make the code cleaner~

**Comment by ahojnnes** [comment] 2016-05-11 05:29
I should be using const's and references correctly, otherwise let me know where. I disagree with `fn(double a)` being equivalent to `fn(const double a)`. The latter gives you guarantees in your code of not messing with the value. I want these guarantees.

**Comment by daleydeng** [comment] 2016-05-11 06:28
For pointer or reference, this does, for value it doesn't, 

fn(double *a) != fn(const double *a) 
but fn(double a) == fn(const double a),  
fn(double a) also cant mass with a due to the copy passing mechanique

never mind~~

**Comment by daleydeng** [comment] 2016-05-11 06:37
In my opinion, only API need to be consted for guarantees, the local variable in function scope need not to be due to its limited influence scope. Remove thoses' unnessccary will make the code cleaner,
 just simple advice~~
Also could refer linux kernel source and the coding style in linux kernel's Documentation which is good~

**Comment by ahojnnes** [comment] 2016-05-11 06:41
Let's kindly disagree on this point. No need for us to converge on good coding practices. Only the code that goes into the main repository should follow the current style.

**Comment by daleydeng** [comment] 2016-05-11 07:51
Allright, when I'm ready for pull request, I'll notice you~

**Comment by daleydeng** [comment] 2016-05-11 08:33
I just made the PR which has been tested again on panorama test dataset~
![image](https://cloud.githubusercontent.com/assets/770506/15174839/20c4f044-1796-11e6-9486-efc70b80c57c.png)

**Comment by ahojnnes** [comment] 2016-06-08 15:18
@daleydeng Sorry, I am very busy at the moment and have not had time to look at this again. I hope to have a free time slot soon to look at your code in more detail.

**Comment by daleydeng** [comment] 2016-06-09 09:58
No problem, help yourself~

**Comment by stephane-lb** [comment] 2016-08-22 20:00
Hi, I would love to test it with my ricoh theta S, how could I do that please ?

**Comment by ahojnnes** [comment] 2016-08-23 08:10
Hi Stephane,

you would have to clone @daleydeng branch and compile it yourself. The rest should be equivalent to the standard procedure, see documentation/tutorial.

Best,
Johannes

**Comment by stephane-lb** [comment] 2016-08-24 21:26
Hi @ahojnnes ,

I tried too do that : 
- I cloned @daleydeng repo
- I switched to origin/cvai
- I compiled
- I executed the gui

And now I don't know what I should select here : 
<img width="272" alt="screen shot 2016-08-24 at 23 23 11" src="https://cloud.githubusercontent.com/assets/5918598/17948643/f6d95842-6a51-11e6-828f-a20e8133a33a.png">

If you could suggest something to me, it would be great.

Thanks for your help,

Stephane

**Comment by stephane-lb** [comment] 2016-09-02 17:59
Hi,

I decide to go throw the command line tutorial and got an error too. I am really sorry, but I have to post here because issues are not opened in @daleydeng  repo.

So this is what I have done :

```
./src/exe/feature_extractor \
    --General.database_path /Users/Stephane-lb/Desktop/myDataset/database.db \
    --General.image_path /Users/Stephane-lb/Desktop/myDataset/images

./src/exe/exhaustive_matcher \
    --General.database_path /Users/Stephane-lb/Desktop/myDataset/database.db  
```

And this is what I got :

```
Matching block [1/1, 1/1] in 27.878s
Elapsed time: 0.46 [minutes]
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const: conn 0x17f53 token 0x1ffffffffffe85
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: Backtrace (at 12467):
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x00007fff8d41f709 CGSDisableUpdateToken + 210
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  1   AppKit                              0x00007fff9d8de420 ___disable_updates_sync_block_invoke_2 + 17
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  2   libdispatch.dylib                   0x00007fff9127e40b _dispatch_client_callout + 8
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  3   libdispatch.dylib                   0x00007fff9127f9f2 _dispatch_barrier_sync_f_invoke + 74
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  4   AppKit                              0x00007fff9d8de2ee NSCGSDisableUpdates + 213
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  5   AppKit                              0x00007fff9d8de124 NSCGSTransactionRunPreCommitActionsForOrder_ + 156
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  6   AppKit                              0x00007fff9d8de06b NSCGSTransactionRunPreCommitActions_ + 21
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  7   AppKit                              0x00007fff9e08cce4 -[_NSCGSTransaction synchronize] + 33
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  8   AppKit                              0x00007fff9e08cf59 NSCGSTransactionSynchronize + 76
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  9   AppKit                              0x00007fff9de77fc5 -[NSSurface syncSurfaceWantsExtendedDynamicRange] + 150
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  10  AppKit                              0x00007fff9d9b02cd -[NSSurface _createSurface] + 677
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  11  AppKit                              0x00007fff9d9afc28 -[NSSurface setFrame:] + 785
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  12  AppKit                              0x00007fff9de780cb __38-[NSSurface syncToViewUnconditionally]_block_invoke + 154
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  13  AppKit                              0x00007fff9d8cd325 NSPerformVisuallyAtomicChange + 147
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  14  AppKit                              0x00007fff9d9af54c -[NSSurface syncToViewUnconditionally] + 100
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  15  AppKit                              0x00007fff9de78164 __37-[NSSurface orderSurface:relativeTo:]_block_invoke + 44
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  16  AppKit                              0x00007fff9d8cd325 NSPerformVisuallyAtomicChange + 147
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  17  AppKit                              0x00007fff9d9af41f -[NSSurface orderSurface:relativeTo:] + 160
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  18  AppKit                              0x00007fff9daa2e56 NSOpenGLContextAttachOnScreenViewSurface + 183
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  19  AppKit                              0x00007fff9ddcf6c7 __27-[NSOpenGLContext setView:]_block_invoke + 192
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  20  AppKit                              0x00007fff9d8cd325 NSPerformVisuallyAtomicChange + 147
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  21  AppKit                              0x00007fff9da8fc0d -[NSOpenGLContext setView:] + 119
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  22  libqcocoa.dylib                     0x0000000105b2af47 -[QNSView setQCocoaGLContext:] + 55
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  23  libqcocoa.dylib                     0x0000000105b63c1d _ZN15QCocoaGLContext11makeCurrentEP16QPlatformSurface + 45
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  24  QtGui                               0x00000001020cbb12 _ZN14QOpenGLContext11makeCurrentEP8QSurface + 162
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  25  exhaustive_matcher                  0x0000000100a77da7 _ZN6colmap14FeatureMatcherC2ERKNS0_7OptionsERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE + 551
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  26  exhaustive_matcher                  0x0000000100a7b5a5 _ZN6colmap24ExhaustiveFeatureMatcherC1ERKNS_14FeatureMatcher7OptionsERKNS0_17ExhaustiveOptionsERKNSt3__112basic_stringIcNS8_11char_traitsIcEENS8_9allocatorIcEEEE + 21
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  27  exhaustive_matcher                  0x0000000100a5e451 main + 513
Sep  2 16:15:34  exhaustive_matcher[31914] <Warning>: void CGSUpdateManager::log() const:  28  libdyld.dylib                       0x00007fff9abe35ad start + 1
```

What did I make wrong ?

Cheers,
Stéphane

**Comment by ahojnnes** [comment] 2016-09-02 18:22
Nothing. This should be ignored and is caused by Qt and not by COLMAP. As long as COLMAP exits without an error, everything should be fine. Let me know if that answers your question.

**Comment by stephane-lb** [comment] 2016-09-02 21:10
@ahojnnes : Thank you ! So in that case that should means that I missed a step to make clomp working with my Ricoh Dataset or that my dataset is not good enough. I will generate a new one tomorrow!

**Comment by daleydeng** [comment] 2016-09-05 14:49
@stephane-lb, to see the difference, you could check the differences with the orignal branch, the ray based modification is there~

**Closed** 2017-04-23 23:55 UTC

**Comment by yuyou** [comment] 2017-09-29 12:38
Hi 

I tried to check @daleydeng's branch (cvai) and see if it works with the latest master branch. One important unit test ([TestRefineEssentialMatrix](https://github.com/daleydeng/colmap/blob/9c6c3092edb7eb4e6d70aa99bf3f999ddbd73c82/src/base/essential_matrix_test.cc#L144)) failed with following big value difference.
```
7/43 Testing: base/essential_matrix_utils_test
7/43 Test: base/essential_matrix_utils_test
Command: "/home/colmap.pano/build/src/base/essential_matrix_utils_test"
Directory: /home/colmap.pano/build/src/base
"base/essential_matrix_utils_test" start time: Sep 29 12:26 UTC
Output:
----------------------------------------------------------
Running 6 test cases...
/home/colmap.pano/src/base/essential_matrix_test.cc(179):
error in "TestRefineEssentialMatrix": check (E - E_refined).norm() <= (E - E_pertubated).norm() failed [2.8186349886258166 > 0.039204384018772402]
````

Does anyone have the same problem? The test environment is:

- Ubuntu 16.04
- Three GeForce GTX 1080 Nvidia cards with CUDA 8.0 (driver 384.69)

**Comment by franmts** [comment] 2017-10-24 17:21
Hi all,
can anyone please confirm if the current cvai branch is funcional with equirectangulars?

**Comment by ahojnnes** [comment] 2017-10-24 17:45
@franmts I have not tried it but if the camera model does not appear in the GUI, it is probably not defined here: https://github.com/colmap/colmap/blob/master/src/base/camera_models.h#L103

**Comment by yuyou** [comment] 2017-10-24 17:50
@franmts I have no problem to get the new camera model in GUI. I can confirm that both GUI and command line modes work with the new camera mode. But as said, the reconstruction result is not plausible. The unit test failed on  "essential_matrix_test".

**Comment by ahojnnes** [comment] 2017-10-24 17:55
@yuyou The `TestRefineEssentialMatrix` should not have an impact on the reconstruction, you can ignore it.

**Comment by franmts** [comment] 2017-10-26 23:59
@yuyou and @daleydeng , do you have windows binaries for this branch? Would be great if you could share that here or on fran.mts@gmail.com to try this out. I'm looking for a benchmark against pix4d and agisoft.

**Comment by ryanismert** [comment] 2018-05-10 04:54
@franmts Did you have any luck testing this?

**Comment by franmts** [comment] 2018-05-10 08:12
Yes, I tested @ryanismert. Compiled after much effort, but I guess I was missing computer horse power to run it, even for smaller dimensions. Software constantly crashed and couldn't proceed.
