### ISSUE TITLE
 error C2300: 'boost::heap::detail::marked_heap_node<std::pair<int,int>>' boost-1_74

### ISSUE THREAD

**Issue by Asher-1** [colmap/colmap#1212] opened 2021-04-24 03:47 UTC
**Describe the bug**
Error output message as follows:
E:\pcl_projects\colmap\src\feature\matching.cc(1064): message : View the instantiation of the function template being compiled“colmap::retrieval::VisualIndex<uint8_
t,128,64>::VisualIndex(void)” reference [E:\pcl_projects\colmap\build\colmap\__build__\src\colmap.vcxproj]
D:\develop\tools\PCL1.11.1\3rdParty\Boost\include\boost-1_74\boost/heap/detail/heap_node.hpp(145,1): error C2300: 'boos
t::heap::detail::marked_heap_node<std::pair<int,int>>' : The class has no destructor, and its name is'~Node' (compiled source file E:\pcl_projects\colmap\src\featur
e\matching.cc) [E:\pcl_projects\colmap\build\colmap\__build__\src\colmap.vcxproj]

**To Reproduce**
    python scripts/python/build.py \
     --build_path E:/pcl_projects/colmap/build \
     --colmap_path E:/pcl_projects/colmap \
     --boost_path "D:/develop/tools/PCL1.11.1/3rdParty/Boost/lib" \
     --qt_path "D:/develop/software/Qt/Qt5.14.2/5.14.2/msvc2017_64" \
     --cuda_path "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1" \
     --cgal_path "D:/develop/tools/CGAL-4.9/build"

**Expected behavior**

**Screenshots**
![I66DTC(_Q WDHRY%378D8HA](https://user-images.githubusercontent.com/16451440/115997104-6f317100-a614-11eb-9825-c41b511b8617.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  chrome
 - Version 10

**Smartphone (please complete the following information):**

**Additional context**
 error C2300: 'boost::heap::detail::marked_heap_node<std::pair<int,int>>' boost-1_74

**Comment by tsattler** [comment] 2021-04-24 07:24
I would try to help, but I don't understand where the problem is. Can you give details, e.g., fill out the form?

**Comment by Asher-1** [comment] 2021-04-25 14:22
Sorry for late reply!
I have update comment above.

**Comment by tsattler** [comment] 2021-04-27 13:34
This seems to be a problem with the boost library and not necessarily with colmap. Did you try to build colmap using vcpkg (https://colmap.github.io/install.html#id3)? 
I don't have a windows machine, but never had problems compiling on mac or linux.

**Comment by Asher-1** [comment] 2021-04-30 01:46
thanks for your help, compiling with vcpkg on windows is ok!

**Comment by tsattler** [comment] 2021-05-08 15:01
Do you want to close the issue then?

**Comment by Asher-1** [comment] 2021-05-10 05:34
ok

**Closed** 2021-05-10 05:34 UTC
