### ISSUE TITLE
when i do feature exaction, colmap was crashed, i don't know why,the image size is 4000*3000,but in another dataset was normal which size is 756*504

### ISSUE THREAD

**Issue by pdycp3** [colmap/colmap#876] opened 2020-05-15 06:53 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pdycp3** [comment] 2020-05-15 06:55
how should i debugging colmap

**Comment by tsattler** [comment] 2020-05-15 13:28
What is the error message that you get from the crash? What are your system specifications? It will be hard to make any statement without this information.

**Comment by pdycp3** [comment] 2020-05-15 13:34
nothing，no information, system crashed, i need to Restart the computer 
![image](https://user-images.githubusercontent.com/45677507/82055922-ca17d400-96f3-11ea-8ca9-c7653f1a1213.png)

**Comment by tsattler** [comment] 2020-05-15 13:37
Well, that can be caused by a lot of reasons (not all of which need to be related to Colmap), e.g., you might have run out of memory. 
Do you know in which stage the crash happened?

**Comment by pdycp3** [comment] 2020-05-15 13:40
feature extraction, when i use this kind of data,  do feature extraction ,i will crash  every time

**Comment by tsattler** [comment] 2020-05-15 13:42
Are you running out of RAM, either on your system or on the GPU?

**Comment by pdycp3** [comment] 2020-05-15 13:44
i didn't choose gpu,because my graphic process  unit is amd

**Comment by pdycp3** [comment] 2020-05-15 13:51
I have enough memory

**Comment by pdycp3** [comment] 2020-05-15 14:03
Confirmed, it is confirmed that the memory is used up, how should I avoid this problem, I successfully extracted the feature points using four images which size is 4000*3000

**Comment by tsattler** [comment] 2020-05-15 14:06
I would recommend to work on lower-resolution images.

**Comment by pdycp3** [comment] 2020-05-15 14:08
thank you

**Comment by tsattler** [comment] 2020-06-22 05:28
@pdycp3 If this solved your problem, please close the issue.

**Closed** 2020-06-22 05:31 UTC
