### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by mchildsCO76** [colmap/colmap#178] opened 2017-07-12 19:56 UTC
I have been attempting to use the latest COLMAP development on my Windows 10 64-bit machines but am getting crashes in theimage_undistorter or dense_stereo step (the exact crash varies despite the same input data). I have tried both the CUDA and non-CUDA versions (non-CUDA doesn't appear to support dense_stereo?). My laptop has a nVidia GTX 1070 card and my desktop has a nVidia GTX 980 card. I get the same problems on both.

I have attached the batch file that I'm using to call the command-line programs, as well as a log file showing the output from the command lines.

I've also tried the GUI and not had any success actually creating a point cloud with that either.

Any suggestions would be greatly appreciated as it looks much more straightforward to use COLMAP on Windows that Theia.
[colmap_batch_file_and_error_log.zip](https://github.com/colmap/colmap/files/1143158/colmap_batch_file_and_error_log.zip)

Thanks,

Mike Childs

**Comment by ahojnnes** [comment] 2017-07-17 06:57
The problem already lies in the feature matching stage. Your GPU has insufficient memory for the number of features in the images: ``ERROR: Feature matching failed. This probably caused by insufficient GPU memory. Consider reducing the maximum number of features.``

Reduce the ``max_num_matches`` option to avoid this problem.

Closing this as resolved, but feel free to reopen.

**Closed by ahojnnes** 2017-07-17 06:57 UTC

**Comment by mchildsCO76** [comment] 2017-07-20 19:22
Thank you for taking a look. I should have reproduced a better sample of the problem as indeed the case I attached had actual error messages rather than a crash. My runs are inconsistent on the same data, with some runs making it all the way to the dense_stereo stage, but some dying much earlier.

I have reduced the max number of features from the default of 8192 to 2048 and attached the new results. In this case the mapper.exe crashed without any hints in the log of what to do. I have attached my new log, along with the updated .bat file I'm using. You can see the actual commands as they are called with the parameters in the log though.

My goal is an easy-to-use interface for this so that users who are not experts in SfM could just drop a bunch of images in and get a point cloud back out. It would be important to be able to handle any type of input without crashing, or at least dying gracefully with an error message I could key on to update parameters. I wouldn't expect a typical end user to know how to adjust things like max feature matches or even know how much GPU memory they have. 

Is something like this reasonable or is a lot of trial-and-error going to be needed?

Thanks,

Mike Childs
[colmap_batch_file_and_error_log.zip](https://github.com/colmap/colmap/files/1163456/colmap_batch_file_and_error_log.zip)

**Comment by AnsisMalins** [comment] 2018-10-03 07:57
Bump. I came up on this thread after googling "colmap crashes". I have the same symptoms: colmap crashes at a seemingly random point in its run. Windows 10, GTX 970.

**Comment by pmd3sallijr** [comment] 2020-04-06 11:45
Hi,
I'm having the same problem I have a window 10 laptop with an integrated Intel Graphics card and a NVIdia Quadro p1000. The latter is CUDA enabled. As soon as I press 'extract' the program crashes. I cant set the default graphics card to be the Nvidia as Colmap has no .exe file it recognises. Please help. Thank you Jim
