### ISSUE TITLE
deregister_image error 

### ISSUE THREAD

**Issue by Bin-ze** [colmap/colmap#2657] opened 2024-07-17 08:05 UTC
When I try to remove the selected images_id image from the scene using the deregister_image api I get an error：
<img width="713" alt="image" src="https://github.com/user-attachments/assets/6e7c840a-1432-4d2d-bdb8-3ec76b75239b">

filter_images_id is the id of the image I need to remove from the scene
I tried to skip the error, but got：
<img width="1450" alt="image" src="https://github.com/user-attachments/assets/7431a043-71f3-4cbe-9f0d-0d44eb7b5b04">

Those outlier cameras weren't what I expected

How can I solve this problem?

**Comment by jaco001** [comment] 2024-07-18 19:17
If nobody write try...
Tip -1: remove those identified frames and create model again (from start)...

**Comment by sarlinpe** [comment] 2024-07-31 13:35
The documentation is really unclear on what (de-)registering an image does - apologies for this. 
1. How is `model` constructed? is it read from disk? 
2. Can you print `model.reg_image_ids()` and check that the corresponding image ID is in this list?
3. Could you provide a self-contained Python code snippet as minimal reproducible example?

Many thanks!

**Comment by sarlinpe** [comment] 2024-08-13 15:36
I cannot reproduce this on my end. I think that you are calling `deregister_image` with an image ID that does not exist.

**Comment by ahojnnes** [comment] 2024-08-16 07:49
Closing this issue as resolved. Please reopen if issue still persists.

**Closed by ahojnnes** 2024-08-16 07:49 UTC
Labels: bug
