### ISSUE TITLE
Vote-and-verify Image Retrieval on Oxford 5k seems wrong

### ISSUE THREAD

**Issue by insikk** [colmap/colmap#288] opened 2018-01-30 13:20 UTC
Currently, I am reproducing vote-and-verify (https://github.com/vote-and-verify/vote-and-verify) with colmap's image retrieval implementation.

I used vocabulary provided in https://demuc.de/colmap/

I used following code. [diff with folked repo insikk/colmap](https://github.com/colmap/colmap/compare/master...insikk:tutorial?expand=1)

I got the result. Without reranking, it agrees with Figure 5 from PGM paper (https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Li_Pairwise_Geometric_Matching_2015_CVPR_paper.pdf)

![image](https://user-images.githubusercontent.com/2110359/35568153-3bb72574-060b-11e8-87bf-c652ad416f60.png)

However, adding vote-and-verify spatial verification gives worse result than noreranking experiment.

|                             | oxf5k (voca_64k) | oxf5k (voca_256k) | oxf5k (voca_1m) | etc                              |
|------------------------|---------------------|---------------------|----------|----------------------------------|
| colmap(no reranking)    |  59.22                | 62.19                     |  63.50    |    |
| colmap(geomverif_1000)    | 46.85                  | 51.15                     | 54.72   |   ??? |

I saw the same trends on this issue (https://github.com/vote-and-verify/vote-and-verify/issues/1). It uses holiday dataset, and adding spatial verification lowers mAP. 

Is it because of not using PGM(pairwise geometric matching. enforcing 1-to-1 matching)?

Have you ever benchmark colmap's image retrieval on popular benchmarks including Oxford5k and Paris6k? What was your result? and do you have any idea why this happens to me?

**Comment by ahojnnes** [comment] 2018-01-30 15:48
How many features per image are you extracting?

**Comment by insikk** [comment] 2018-01-31 06:41
@ahojnnes Oops. I found out that I used original query image instead of using cropped region. The updated result is like this. 

* Add cropped query version
* Add column for using 200k vocab trained on Paris6k
    * I also succeed to generate 200k vocab on Paris6k with colmap vocab builder. It took almost 2 days. Was it slow when you run vocab builder? 
* For geomverif_1000, we only use 1000 rank list. Based on current implementation we lose marginal AP for the rest 4062 retrieval results, which is small by the way. 


|                             | oxf5k (voca_64k) | oxf5k (voca_200k_paris) | oxf5k (voca_256k) | etc                              |
|------------------------|---------------------|---------------------|----------|----------------------------------|
| colmap(no reranking)    |  59.22     | 61.73| 62.22                     |    |
| colmap(geomverif_1000)    | 46.71   |   52.34   | 50.87                |   ??? |
| colmap(crop, no reranking)    |  61.66  | 62.37 | 63.07                     |    |
| colmap(crop, geomverif_1000)    | 49.25  |  52.55 | 51.85         | ??? |

I used default setting on `feature_extractor`
Here is command that I issued. 
`../build/src/exe/feature_extractor --database_path ../ir_demo/database.db --image_path ../ir_demo/images`

Few lines of output is look like this:
```
==============================================================================
Feature extraction
==============================================================================

Processed file [1/5062]
Name:            all_souls_000000.jpg
Dimensions:      683 x 1024
Camera:          1 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        7845
Processed file [2/5062]
Name:            all_souls_000005.jpg
Dimensions:      1024 x 768
Camera:          5 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        743
Processed file [3/5062]
Name:            all_souls_000002.jpg
Dimensions:      677 x 1024
Camera:          3 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        3112
Processed file [4/5062]
Name:            all_souls_000006.jpg
Dimensions:      768 x 1024
Camera:          6 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        4138
Processed file [5/5062]
Name:            all_souls_000003.jpg
Dimensions:      768 x 1024
Camera:          4 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        5049
Processed file [6/5062]
Name:            all_souls_000007.jpg
Dimensions:      768 x 1024
Camera:          7 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        4065
Processed file [7/5062]
Name:            all_souls_000008.jpg
Dimensions:      1024 x 768
Camera:          8 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        4771
Processed file [8/5062]
Name:            all_souls_000001.jpg
Dimensions:      1024 x 683
Camera:          2 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        9613
Processed file [9/5062]
Name:            all_souls_000013.jpg
Dimensions:      768 x 1024
Camera:          12 (SIMPLE_RADIAL)
Focal Length:    1228.80px (Default)
Features:        3799
```

It seems 5000 features are extracted per image on average.

**Comment by ahojnnes** [comment] 2018-01-31 06:50
The parameters of the geometric verification have been tuned for ~2000 features per image. But there might also be a bug in the implementation, since I reimplemented the geometric verification and also did not implement 1-to-1 matching.

**Comment by insikk** [comment] 2018-02-01 02:57
I tried few more experiments including 1-to-1 matching. 


|                             | oxf5k (voca_64k) | oxf5k (voca_200k_paris) | oxf5k (voca_256k) | etc                              |
|------------------------|---------------------|---------------------|----------|----------------------------------|
| vote-verify(no reranking)    |  -     | 76.2 | -                 |    |
| vote-verify(FSM)    |  -     | 79.9 | -                 |    |
| vote-verify(HPM)    |  -     | 73.4 | -                 |    |
| vote-verify(ADV)    |  -     | 78.5 | -                 |    |
| vote-verify(PGM)    |  -     | 76.0| -                 |    |
| vote-verify(ours)    |  -     | 80.1 | -                 |    |
| vote-verify(ours+Eff.Inl.Post)    |  -     | 79.8 | -                 |    |
| colmap(no reranking)    |  59.22     | 61.73| 62.22                     |    |
| colmap(geomverif_1000)    | 46.71   |   52.34   | 50.87                |   ??? only 1000 rank |
| colmap(1-to-1 geomverif_1000)    | 50.01   |   52.31   | 54.63                |  only 1000 rank |
| colmap(crop, no reranking)    |  61.66  | 62.37 | 63.07                     |    |
| colmap(crop, geomverif_1000)    | 49.25  |  52.55 | 51.85         | ??? only 1000 rank|
| colmap(crop, 1-to-1 geomverif_1000)    | 54.17  |  55.94 | 56.79         | only 1000 rank|
| colmap(crop, 1-to-1 geomverif_1000)    | 54.45 | 56.24  | 57.07         | use 5062 rank|

I suspect that even no-reranking version has large performance difference. 

Is it because of features, and other things?

* HesAff v.s. DoG SIFT
* SIFT v.s. RootSIFT

Any other things you want to tell me to help reproduce the reported result?

I tried limiting max_num_features to 2000. It speed up, but reduces performance by small maring. ~0.xx %

**Comment by ahojnnes** [comment] 2018-02-02 20:55
I am looking into this right now. I'll get back to you. There is clearly a bug in the COLMAP version that I need to track down.

**Comment by trueprice** [comment] 2018-02-03 00:25
So, it looks like the implemented method for effective inlier counting is different from our original implementation. @insikk could you try just removing the EIC and let us know if that improves the results?

I.e., just return best_num_inliers in the VoteAndVerify function: https://github.com/colmap/colmap/blob/b44473edb70704c5f82a5dd181015d7c5d767f1e/src/retrieval/vote_and_verify.cc#L382

**Comment by insikk** [comment] 2018-02-05 11:20
@trueprice I followed your advice, but there was no luck. 
With [the patch](https://github.com/colmap/colmap/commit/2af94a6a034031921a2e1ec65de13050db61b2c5), I got following: (Bold is the updated result)

* Using inliers instead of effective inliers make performance slightly worse

|                             | oxf5k (voca_64k) | oxf5k (voca_200k_paris) | oxf5k (voca_256k) | etc                              |
|------------------------|---------------------|---------------------|----------|----------------------------------|
| vote-verify(no reranking)    |  -     | 76.2 | -                 |    |
| vote-verify(ours)    |  -     | 80.1 | -                 |    |
| vote-verify(ours+Eff.Inl.Post)    |  -     | 79.8 | -                 |    |
| colmap(crop, no reranking)    |  61.66  | 62.37 | 63.07                     |    |
| colmap(crop, 1-to-1 geomverif_1000, Inl)    | **54.05** | **56.14**  | **56.94**         | use 5062 rank|
| colmap(crop, 1-to-1 geomverif_1000, Eff.Inl.Post)    | 54.45 | 56.24  | 57.07         | use 5062 rank|


An interesting point is that, I reproduced other SIFT BoW based image retrieval system (https://github.com/tsattler/geometric_burstiness), and I got same trend.
Best performance on noreranking, and eff.inlier, inlier in order. Here is the issue link (https://github.com/tsattler/geometric_burstiness/issues/7)

If this is not intended (I hope not), there is definitely a bug in this code. 

Do you have any suggestion for the next task to do to isolate the potential bug?

I was thinking about visualizing the matching result. Because reranking seems pushing up non-relevant images to top ranks. That explains lowering mAP in general when using spatial verification. See below results. 

## No reranking. Query. all_souls_1.png. Top 20
![image](https://user-images.githubusercontent.com/2110359/35801867-3bacd9c0-0ab1-11e8-941f-ea65be714806.png)

## Top 1000 reranked. Query. all_souls_1.png. Top 20
![image](https://user-images.githubusercontent.com/2110359/35802023-d589ee48-0ab1-11e8-86b9-229f2ddcecba.png)

**Comment by trueprice** [comment] 2018-02-05 14:40
Thanks for trying it out. In the meantime, I've also been able to reproduce the behavior on my machine. Based on the performance, there definitely has to be a bug in the retrieval, likely in the BoW retrieval itself. I'll spend some time poking at the code to see if I can find anything.

It's strange that you're seeing the same behavior with the geometric burstiness code -- our original implementation builds from that codebase. (Perhaps this is an issue in some way with the features being used?) For debugging, the next thing I'd suggest is to visualize the final set of matches for each returned image -- do the final correspondences between the query and database images make sense? Do we routinely observe many features that ought to be matched, but are not?

If your experiments are time-sensitive and we don't find the problem in a day or two, we should be able to provide you with the code and data we used in our original submission.

**Comment by trueprice** [comment] 2018-02-07 04:26
Just to update, I've run more tests with upright features, which we used previously, and saw a few percent improvement. We're now looking into using the same retrieval parameters as previously (e.g., increasing the number of nearest-neighbor checks in flann, which should increase precision). Hopefully, this solves the problem, up to potentially a slight decrease in mAP due to not using affine features. I'll post here when I have full results to share.

**Comment by insikk** [comment] 2018-02-13 03:28
@trueprice Hi there, I was taking break for a while, and I'm back to work now. How things are going?

According to the source code for image retrieval in Colmap, it does not use affine features, which is using x, y, a, b, c. I understood that changing SIFT Keypoint to Hessian Affine keypoints may boost up few percent in mAP. Implementing it is quite obvious. Maybe I can try this idea. 

I have a question. What do you mean by "upright features"? This is unfamiliar term to me. What is it? Can you explain more about it?

**Comment by ahojnnes** [comment] 2018-02-13 04:52
@insikk Upright features mean that you fix the orientation of features to be zero. This works for most images in Oxford/Paris since most of them are taken in upright orientation. At the moment, we are experimenting with the current pipeline. We couldn't find a bug in the code, but it seems the results primarily depend on the employed features. We could push the pure retrieval performance to ~68% with that. We are still trying to figure out why it is not working the way it should and will get back to you. For the worst, you will just get our data. Let us know if there are any insights from your side. Thanks.

**Comment by trueprice** [comment] 2018-02-13 05:05
Hi @insikk, just to add, I've found the [VLFeat tutorial](http://www.vlfeat.org/overview/covdet.html) helpful for understanding covariant features. BTW, COLMAP is able to extract affine features using --SiftExtraction.estimate_affine_shape (upright affine features resulted in the ~68% mAP). For the ACCV paper, we used Michal Perdoch's [Hessian Affine feature extractor](https://github.com/perdoch/hesaff).

**Comment by ahojnnes** [comment] 2018-02-23 17:42
@insikk We could reproduce the results and will share the details soon with you. So, stay tuned over the next days. Thanks again for helping us with this!

**Comment by insikk** [comment] 2018-02-26 05:43
Thank you for your implementation. Now spatial verification increases mAP further from its counterpart of not using spatial verification. I also confirmed with my eyes. I measured with various vocab sizes that are available to me. 

From this pull request (https://github.com/colmap/colmap/pull/314), below measures are obtained from  commit https://github.com/colmap/colmap/pull/314/commits/814d8d975ee15965fc1bafd813ed8d972e011ce1

See [here](https://github.com/insikk/colmap/tree/dev) for image retrieval tutorial, evaluation, and visualization  python notebook.

|                             | oxf5k (voca_64k) | oxf5k (voca_200k_paris) | oxf5k (voca_256k) | etc                              |
|------------------------|---------------------|---------------------|----------|----------------------------------|
| vote-verify(no reranking)    |  -     | 76.2 | -                 |    HesAff |
| vote-verify(ours)    |  -     | 80.1 | -                 |  HesAff  |
| vote-verify(ours+Eff.Inl.Post)    |  -     | 79.8 | -                 |  HesAff  |
| colmap(crop, no reranking)    |  57.43  | 60.93 | 61.02                     |    |
| colmap(crop, 1-to-1 geomverif, Eff.Inl.Post)    | 67.90 | 69.67  | 67.94         | |

## Visualization (oxf5k (voca_200k_paris))
**no reranking**
![image](https://user-images.githubusercontent.com/2110359/36654914-f1fd8e02-1b02-11e8-9787-e9fb4db1bc27.png)


**reranking (spatial verification)**
![image](https://user-images.githubusercontent.com/2110359/36654935-083b3df4-1b03-11e8-92bf-602e49121ec6.png)


Next step will be using Hessian Affine features, and see if it improve mAP further. 
To do that loading externally trained vocab would be useful feature. https://github.com/colmap/colmap/issues/287

**Comment by trueprice** [comment] 2018-02-26 06:18
Hi @insikk,

Great to hear that you've verified the improvement, and thanks again for your help! Following up from my own experience in testing this, I see ~74.3 mAP for uncropped image retrieval using COLMAP for extraction (upright, affine features) and matching (1024 checks in the nearest neighbor search) with spatial verification. Hessian affine features should provide a few percent improvement, as well.

If you need it, I've written a Python script to load pre-computed visual words, Hamming embeddings, and the projection matrix into COLMAP's vocabulary tree format. I also have a script to convert affine features into a COLMAP database.

**Comment by insikk** [comment] 2018-03-09 09:26
@trueprice I am glad to see that mAP is about 74.3. Can you point out where can I find the Python script?
I also want to try with different features. Your conversion script will come in handy :+1:

**Comment by trueprice** [comment] 2018-03-12 18:16
Hi @insikk, I've created [a gist](https://gist.github.com/trueprice/eb1f55a3ff4fbca01b07e69d125368b5) to get you started with uploading features and visual words to COLMAP. You'll likely need to adapt the files to suit your needs. Let me know if you have any questions.

Also, is this issue ready to be closed?

**Comment by insikk** [comment] 2018-03-13 03:21
@trueprice Thank you for sharing your code. I think including these code to Colmap repo is also good idea because I had been struggled how to separately run image retrieval pipeline with Colmap. 

Anyway, I was able to achieve 75.02 mAP with your suggestion (using upright, affine features for both building vocab_tree and feature extraction for query and db images. Using num_checks=1024 for colmap programs)

|                             | oxf5k (voca_200k_paris) |  etc                              |
|------------------------|------|----------------------------------|
| vote-verify(no reranking)    | 76.2   |    HesAff |
| vote-verify(ours)     | 80.1       |  HesAff  |
| vote-verify(ours+Eff.Inl.Post)    | 79.8   |  HesAff  |
| colmap(crop, no reranking)   | 65.68   |   Upright. Aff. |
| colmap(crop, 1-to-1 geomverif, Eff.Inl.Post) | 75.02   |Upright. Aff. |

Next step will be experimenting with HesAff feature to squeeze out more mAP, but I think this issue can be closed. 

Again thank you for your supports. :+1: :+1: :+1:  :smile:

**Comment by ahojnnes** [comment] 2018-03-13 06:45
Great, thanks for the feedback. Closing this issue as resolved now. I assume you also pulled the latest changes from Github? We made quite a few bug fixes to the code recently.

**Closed by ahojnnes** 2018-03-13 06:45 UTC
