### ISSUE TITLE
Can't run feature extraction, but can run auto reconstruction

### ISSUE THREAD

**Issue by gowanting** [colmap/colmap#529] opened 2018-12-03 05:30 UTC
It looks like a little bit weird, because I can't run it step by step, which means I saved a project, and then, when I click the 'feature extraction', it has no response at all. 

But when I try auto reconstruction, it works well, and I can see it already finished 'feature extraction' etc.

  Desktop
 - Linux 18.04

**Comment by ahojnnes** [comment] 2018-12-06 07:46
Not sure what is happening. The final result of auto reconstruction in the sparse folder should have relatively few outliers, but it will very likely still contain a small fraction of outliers.

**Comment by zhuoliang** [comment] 2018-12-14 22:18
Got the same problem. The problem is caused by "ui/feature_extraction_widget.cc, line 304":
_static_cast<ExtractionWidget*>(tab_widget_->currentWidget())->Run();

Looks like you need to call QScrollArea::widget() to access its widget.
Link: http://doc.qt.io/qt-5/qscrollarea.html

A native fix below works for me (I know little about Qt, and there could be other better fix):
_static_cast<ExtractionWidget*>(
static_cast<QScrollArea*>(tab_widget_->currentWidget())->widget())->Run();

**Comment by gowanting** [comment] 2018-12-15 16:41
> Got the same problem. The problem is caused by "ui/feature_extraction_widget.cc, line 304":
> _static_cast<ExtractionWidget*>(tab_widget_->currentWidget())->Run();
> 
> Looks like you need to call QScrollArea::widget() to access its widget.
> Link: http://doc.qt.io/qt-5/qscrollarea.html
> 
> A native fix below works for me (I know little about Qt, and there could be other better fix):
> _static_cast<ExtractionWidget*>( static_cast<QScrollArea*>(tab_widget_->currentWidget())->widget())->Run();

**Comment by gowanting** [comment] 2018-12-15 16:47
> Got the same problem. The problem is caused by "ui/feature_extraction_widget.cc, line 304":
> _static_cast<ExtractionWidget*>(tab_widget_->currentWidget())->Run();
> 
> Looks like you need to call QScrollArea::widget() to access its widget.
> Link: http://doc.qt.io/qt-5/qscrollarea.html
> 
> A native fix below works for me (I know little about Qt, and there could be other better fix):
> _static_cast<ExtractionWidget*>( static_cast<QScrollArea*>(tab_widget_->currentWidget())->widget())->Run();

You mean change this before build? or after build?
I changed this after build, it stiil not work.
I changed this before build, it occurs such errors:

[ 82%] Building CXX object src/CMakeFiles/colmap.dir/ui/feature_extraction_widget.cc.o
/home/wantinf/colmap/src/ui/feature_extraction_widget.cc: In member function ‘void colmap::FeatureExtractionWidget::Extract()’:
/home/wantinf/colmap/src/ui/feature_extraction_widget.cc:305:29: error: ‘tab_widget’ was not declared in this scope
   static_cast<QScrollArea*>(tab_widget->currentWidget())->widget())->Run();
                             ^
src/CMakeFiles/colmap.dir/build.make:1838: recipe for target 'src/CMakeFiles/colmap.dir/ui/feature_extraction_widget.cc.o' failed
make[2]: *** [src/CMakeFiles/colmap.dir/ui/feature_extraction_widget.cc.o] Error 1
CMakeFiles/Makefile2:963: recipe for target 'src/CMakeFiles/colmap.dir/all' failed
make[1]: *** [src/CMakeFiles/colmap.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhuoliang** [comment] 2018-12-15 17:32
Change and rebuild.

Replace "tab_widget" with tab_widget_

**Comment by gowanting** [comment] 2018-12-16 02:50
> Change and rebuild.
> 
> Replace "tab_widget" with tab_widget_

Wow, amazing, it works, sincerely thanks for your help!

**Comment by ahojnnes** [comment] 2018-12-18 13:49
This is now fixed in the latest commit in the dev branch. Thanks for reporting.

**Closed by ahojnnes** 2018-12-18 13:49 UTC
