### ISSUE TITLE
Fusion problem

### ISSUE THREAD

**Issue by alexsmartens** [colmap/colmap#106] opened 2017-04-13 17:13 UTC
Hi I have the following problem while performing fusion on Ubuntu 16.04:

```
./src/exe/colmap
Problem creating accessible interface for:  QWindow(0x236a240) 
Make sure to deploy Qt with accessibility plugins.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1492102865 (unix time) try "date -d @1492102865" if you are using GNU date ***
PC: @     0x7ff630d35428 gsignal
*** SIGABRT (@0x3e800007381) received by PID 29569 (TID 0x7ff606eda700) from PID 29569; stack trace: ***
    @     0x7ff634421390 (unknown)
    @     0x7ff630d35428 gsignal
    @     0x7ff630d3702a abort
    @     0x7ff63167784d __gnu_cxx::__verbose_terminate_handler()
    @     0x7ff6316756b6 (unknown)
    @     0x7ff631675701 std::terminate()
    @     0x7ff6316a0d38 (unknown)
    @     0x7ff6344176ba start_thread
    @     0x7ff630e0682d clone
    @                0x0 (unknown)
Aborted (core dumped)
```

 What would you suggest for fixing the problem?

**Comment by ahojnnes** [comment] 2017-04-13 17:18
Have you tried using the command-line interface of COLMAP? For the fusion, you should use the dense_fuser executable. More information can be found in the documentation. Let me know if that works for you.

**Comment by alexsmartens** [comment] 2017-04-15 01:09
I am trying to use the command-line interface. I started from scratch, cannot get to this stage yet. I am at the Dense mapper stage, have #107 issue

**Comment by alexsmartens** [comment] 2017-04-15 01:28
This is what I have when I attempt to make fusion on the COLMAP GIU output:  

```
$./src/exe/dense_fuser     --workspace_path /media/...my_path...//Dense\ model    
 --workspace_format COLMAP     
--input_type geometric     
--output_path /media/...my_path.../Dense\ model/point-cloud.ply

StereoFusion::Options
---------------------
min_num_pixels: 5
max_num_pixels: 1000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10

Reading workspace...
Reading configuration...
WARNING: Ignoring image IMG_8938.JPG, because input does not exist.
WARNING: Ignoring image IMG_8931.JPG, because input does not exist.
...
...
WARNING: Ignoring image IMG_9166.JPG, because input does not exist.
WARNING: Ignoring image IMG_9167.JPG, because input does not exist.
Number of fused points: 0
Elapsed time: 0.061 [minutes]
Writing output: /media/...my_path.../Dense model/point-cloud.ply
```

How to specify the image path?

**Comment by ahojnnes** [comment] 2017-04-18 15:18
``--input_type geometric`` requires to run the pipeline with ``--input_type photometric`` first. Did you do that?

**Comment by alexsmartens** [comment] 2017-04-18 17:37
No, I did not do that. 
I followed the [Command-line guide ](https://colmap.github.io/cli.html )
`--input_type geometric` is the penultimate step, and there is nothing about -`-input_type photometric`. 

If I understand you correctly, I should run `--input_type photometric` right before running `--input_type geometric` with this code:
```
$./src/exe/dense_fuser     --workspace_path /media/...my_path...//Dense\ model    
 --workspace_format COLMAP     
--input_type photometric   
--output_path /media/...my_path.../Dense\ model/point-cloud.ply
```
Then, I guess, I need to run `--input_type geometric code`, and the last step is to run `dense_mesher`.

Does this sound correct, Johannes? Do you have any other suggestion?

**Comment by alexsmartens** [comment] 2017-04-25 15:57
Hi @ahojnnes,
can you help to finish the dense reconstruction, please
My idea did not work out

**Comment by ahojnnes** [comment] 2017-05-02 16:49
Did you resolve the issue?

**Comment by alexsmartens** [comment] 2017-05-08 15:02
Hi @ahojnnes ,

No, the issue is not resolved yet. I'm guessing that the initial problem might be the issue #105 , which you closed but I cannot resolve it. 

### **Issue #105:**
I tried to compile Colmap with Eigen 3.3.3 and Eigen 3.3.2. And I had the same test failure #105. It's a bit frustrating as it takes hours to compile Colmap and this does not help.
Anyways, I found @lfrschkn suggested to compile Colmap with Eigen 3.2.0-8 as well as @theNded suggested to play around with Eigen 3.2.x in the issue #87. I am going to try this options asap. Will let you know how it goes afterwards

Any help will be appreciated,
thanks

**Comment by alexsmartens** [comment] 2017-05-09 15:05
The issue #105 is solved after compiling Colmap of the currently updated version.
It is compiled perfectly with all of the last Eigen versions.

This problem (Fusion problem #106) is still on

**Comment by ahojnnes** [comment] 2017-05-22 12:06
Thanks for the feedback. Closing this now.

**Comment by is03wlei** [comment] 2017-05-24 02:56
@
It seems this issue has not been resolved yet. Why did you close it?
I also met with the same problem. I ran the pipeline with --input_type photometric first. But got the same warnings.

**Comment by ahojnnes** [comment] 2017-05-24 07:04
I need a concrete error message, a set of commands and a dataset to reproduce, since I cannot reproduce this issue on my machine.

**Comment by is03wlei** [comment] 2017-05-24 07:49
I debugged it and found it failed in HasImage(), concretely in GetDepthMapPath().
This file "./dense/0/stereo/depth_maps/scene010053.jpg.geometric.bin" doesn't exist.
There is only "./dense/0/stereo/depth_maps/scene010053.jpg.photometric.bin".

**Comment by ahojnnes** [comment] 2017-05-24 07:52
Then, my guess is that you used ``./dense_fusion --input_type geometric ...`` even though you only computed photometric output?

**Comment by is03wlei** [comment] 2017-05-24 07:53
I think so. But how to generate geometric output?

**Comment by ahojnnes** [comment] 2017-05-24 07:55
There should be a ``run-colmap-photometric.sh`` and ``run-colmap-geometric.sh`` in the workspace folder. Those examples should work out of the box.

**Comment by is03wlei** [comment] 2017-05-24 07:58
Thanks. I think it's this parameter "--DenseStereo.geom_consistency true" that enables geometric output.

**Comment by ahojnnes** [comment] 2017-05-24 08:07
Yes, but you first need to compute the photometric before running the geometric output. As shown in the shell script examples, which is also described in the documentation.

**Comment by ahojnnes** [comment] 2017-05-30 09:08
The procedure should be simplified with the latest commits in the master and dev branches. You only need to run the ``dense_stereo`` executable once now for geometric consistency. Closing this issue as resolved for now but feel free to reopen in case problems persist.

**Closed by ahojnnes** 2017-05-30 09:08 UTC
