### ISSUE TITLE
broken GUI on lubuntu 17.04

### ISSUE THREAD

**Issue by HybridDog** [colmap/colmap#135] opened 2017-06-04 19:38 UTC
When l run colmap, it looks like this:
![2017-06-04-213627_1024x600_scrot](https://cloud.githubusercontent.com/assets/3192173/26764788/f32e71ae-496d-11e7-9d70-7083f267a177.png)
l clicked on the help menu list, there's black text on a black background.

**Comment by ahojnnes** [comment] 2017-06-04 21:34
No idea what's happening on your system. Can you start from the command line and check whether there are any warnings / errors printed in the terminal?

**Comment by HybridDog** [comment] 2017-06-05 08:32
There're the typical lubuntu style theme warnings.
```
(colmap:12691): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: not a number

(colmap:12691): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: Expected a string.

(colmap:12691): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:815:10: not a number

(colmap:12691): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:815:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(colmap:12691): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1953:14: not a number

(colmap:12691): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1953:14: Expected a string.

(colmap:12691): Gtk-WARNING **: Theme parsing error: nautilus.css:50:71: Using one color stop with linear-gradient() is deprecated.

(colmap:12691): Gtk-WARNING **: Theme parsing error: nautilus.css:51:71: Using one color stop with linear-gradient() is deprecated.

(colmap:12691): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:252:14: not a number

(colmap:12691): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:252:14: Expected a string.
```
In my opintion it's strange, lubuntu artwork causes warnings, most of them can be easily fixed, but it looks like they don't even bother fixing the warnings before releasing the software for the official non-LTS lubuntu release. 

Anyway, when running colmap with another theme, l don't get warnings but it's still broken.
Tested with `Industrial` theme:
![2017-06-05-102945_1024x600_scrot](https://cloud.githubusercontent.com/assets/3192173/26776626/3038a9c2-49da-11e7-986f-46cd7c2aaf75.png)

**Comment by ahojnnes** [comment] 2017-06-05 09:09
I will try to compile it under 17.04 soon and see whether I can reproduce the issue.

**Comment by ahojnnes** [comment] 2017-06-18 18:54
I recompile's with Ubuntu 17.04 but using the Unity desktop and everything looks fine for me. I will check with LXDE soon but I feel that this is caused by Qt rather than Colmap. Thanks for your feedback.

**Comment by HybridDog** [comment] 2017-07-08 11:01
l just noticed that l have the same problem with ReText.

**Comment by ahojnnes** [comment] 2017-07-13 09:44
Closing this issue then as unrelated to COLMAP directly but rather a Qt or OS issue. Thanks for reporting anyway.

**Closed by ahojnnes** 2017-07-13 09:44 UTC
