### ISSUE TITLE
ransac.h causing crash

### ISSUE THREAD

**Issue by cpyarger** [colmap/colmap#476] opened 2018-09-04 15:16 UTC
on windows 10 I get the following with GPU disabled

==============================================================================
Registering image #15 (3)
==============================================================================

  => Image sees 35 / 236 points
F0904 08:12:05.872309 14160 ransac.h:65] Check failed: max_error > 0 (0 vs. 0)
*** Check failure stack trace: ***

**Comment by ahojnnes** [comment] 2018-09-04 16:01
I assume, you manually changed the options and set the error to 0?

**Comment by cpyarger** [comment] 2018-09-04 17:18
I set the options in the program. I never manually set the error

**Comment by ahojnnes** [comment] 2018-09-06 06:53
Can you start from a fresh folder/project and retry? Don't set any of the options manually in this case. I cannot reproduce the issue on my machine. Are you using the automatic reconstruction?

**Comment by krikru** [comment] 2018-09-08 12:47
I have the same problem on Windows 10 when performing Automatic reconstruction with COLMAP 3.5. I don't set any parameters myself so GPU is enabled.

Here is the full console output when running COLMAP.bat from the Command Prompt:

```
F0908 14:30:35.588809 12012 ransac.h:65] Check failed: max_error > 0 (0 vs. 0)
*** Check failure stack trace: ***
F0908 14:30:0F359.000008 588809 00014: F30:6668 ransac.h:35.     965F] Check failed: max_error > 0 (0 vs. 0) 588809 00008 097032 ransac.h8 14:0F65] Check failed: max_error > 0 (0 vs. 0) 30:0914:08 35.3014::3035:.588809 35.588809 588809 18428 1060ransac.h 70:ransac.h :ansac.h :6565] ] 65Check failed: ] max_error > 0 (0 vs. 0)                       Check failed:   max_error > 0 (0 vs. 0) F0908 14:30:35.588809 17336 ransac.h:65] Check failed: max_error > 0 (0 vs. 0)
*** Check failure stack trace: ***
F0908 14:30:0F359.000008 588809 00014: F30:6668 ransac.h:35.     965F] Check failed: max_error > 0 (0 vs. 0) 588809 00008 097032 ransac.h8 14:0F65] Check failed: max_error > 0 (0 vs. 0) 30:0914:08 35.3014::3035:.588809 35.588809 588809 18428 1060ransac.h 70:ransac.h :ansac.h :6565] ] 65Check failed: ] max_error > 0 (0 vs. 0)                       Check failed:   max_error > 0 (0 vs. 0) F0908 14:30:35.588809 17336 ransac.h:65] Check failed: max_error > 0 (0 vs. 0)
*** Check failure stack trace: ***

```

**Comment by ahojnnes** [comment] 2018-09-08 17:51
Thanks, I will try to replicate this.

**Comment by ahojnnes** [comment] 2018-09-08 17:52
Would you be able to share the images with me?

**Comment by krikru** [comment] 2018-09-08 23:38
Sure – check your email!

**Comment by ahojnnes** [comment] 2018-09-09 16:56
Thanks for reporting, this should be fixed now. I cannot recompile the Windows binaries until next Monday though.

**Comment by ahojnnes** [comment] 2018-09-09 16:56
Let me know in case the latest commit did not fix your issues.

**Closed by ahojnnes** 2018-09-09 16:56 UTC

**Comment by ahojnnes** [comment] 2018-09-18 07:06
The windows binaries are now updated for the 3.5 release, the Mac binaries will follow shortly.
