### ISSUE TITLE
Registering image with wrong index

### ISSUE THREAD

**Issue by rdiazgar** [colmap/colmap#20] opened 2016-08-06 03:57 UTC
Hi

I'm finding a strange behavior with colmap. I'm trying to reconstruct a dataset (the Dubrovnik one) and from the log file I see an attempt to register an image twice in totally separate moments. For instance, at some point image #6455 (3183) is resectioned successfully and the program continues. After a while, the same image seems to be resectioned again: image #6455 (6721). 

There's something weird going on because I think this is not the same image, but another one with a different id. When finishing, colmap reports that the last image registered was image #3817 (6800), making a total of 6800 images. When I export the model to bundler, it only exports 6677 images. I think there must be a bug somewhere that retrieves the next image with the wrong id, so that the image counter between parenthesis is counting right, but it's choosing an image id that has been already registered.

Please let me know if I can provide any extra information.

Regards
Raul

**Comment by ahojnnes** [comment] 2016-08-06 04:55
Hi Raul,

Thanks for the report and I am surprised if this is happening. Can you share the database with me? You can send me an email, if you prefer.

I will try to look into this later today or tomorrow!

Best,
Johannes

**Comment by ahojnnes** [comment] 2016-08-08 05:55
Hi Raul,

Thanks for sharing the files with me. I found out that this is not a bug but a feature :-)

The "strange" behavior is caused by the fact that COLMAP automatically filters registered images with bogus camera parameters. First, this causes the final model to have fewer registered images (Notice the output of the last global bundle adjustment, it says "124 filtered images"). Second, COLAMP tries to register the filtered images again later. You could disable the filtering by loosening the constraints in `Reconstruction options > Filter > ...`.

I hope this helps and let me know if you have any other questions.

Cheers,
Johannes

**Comment by rdiazgar** [comment] 2016-08-09 18:00
Hi

So as far as I understand, it is not a problem of confusing image_ids, 
but rather that the number in parenthesis shown in the logs is the 
number of total registration attempts, regardless of whether that image 
is filtered out later.

What is exactly the definition of bogus parameters?

Raul

**Comment by ahojnnes** [comment] 2016-08-09 19:17
Camera parameters are bogus, if: a) the field of view is abnormal (min_focal_length_ratio, min_focal_length_ratio), b) the distortion coefficients are abnormal (max_extra_param), see https://github.com/colmap/colmap/blob/master/src/base/camera_models.h#L424

Cheers, Johannes

**Comment by ahojnnes** [comment] 2016-08-14 07:42
Hi Raul,

I will close this issue for now. Feel free to reopen, if any questions remain.

Best,
Johannes

**Closed by ahojnnes** 2016-08-14 07:42 UTC
