### ISSUE TITLE
colmap point triangulator does not work after the PR #2575. Addition of Observation Manager.

### ISSUE THREAD

**Issue by shounaknaik** [colmap/colmap#2670] opened 2024-07-24 22:19 UTC
**Problem**
Addition of Observation Manager causes the `colmap point_triangulator` code to fail.

**To Reproduce**
Run `colmap point_triangulator` with the required flags. 

**Error**
pthread related error
![image](https://github.com/user-attachments/assets/cd2b6f1a-0703-47ef-993d-2ceef5e4bd5d)

**Environment:**
 - OS: Ubuntu 22.04
 - COLMAP Version 3.10 with CUDA
 
 If I revert back to commit ID with SHA a692b6813ce76c3bffc60db067435bc80c71488f, the command works. 
 I create my `database.db` using all the necessary information and the format of this database might have changed from February. 
 I am sharing this workaround if anyone is facing a similar issue.

**Comment by sarlinpe** [comment] 2024-07-31 14:28
Thanks for reporting this issue. The database format has not significantly changed since February. I cannot reproduce this issue. Would you mind sharing the input model and database?

**Comment by phuong-dinhmai** [comment] 2024-08-05 08:50
I also got the same problems when trying to reconstruct a sparse model from known camera poses following this article: https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses. Is there any updated yet?

**Comment by sarlinpe** [comment] 2024-08-10 08:58
Again, could you share the data required to reproduce this issue? thanks!

**Comment by shounaknaik** [comment] 2024-08-13 00:01
Hey @sarlinpe, sorry for the delay.
I might be wrong in my implementation. But I am facing the issue when I run the `point_triangulator` as mentioned in the FAQ page of this framework. I am trying to reconstruct a model from known camera poses.
`
colmap point_triangulator \
    --database_path $PROJECT_PATH/database.db \
    --image_path $PROJECT_PATH/images
    --input_path path/to/manually/created/sparse/model \
    --output_path path/to/triangulated/sparse/model`
    
 I am attaching a small zip file by which you can replicate the issue.
 My solution was to revert `colmap` version to the previous version as described
 
 
[colmap_issue.zip](https://github.com/user-attachments/files/16592836/colmap_issue.zip)

**Comment by sarlinpe** [comment] 2024-08-13 15:28
I cannot reproduce this issue with the given data, at both 3.10 and [HEAD](https://github.com/colmap/colmap/commit/6247ca0673b28554cd10b89cbac4dfe0b9ec9837):
```
> colmap point_triangulator --database_path colmap_issue/database.db --image_path colmap_issue/images --input_path colmap_issue/ --output_path out
I20240813 17:21:41.614025 130027 misc.cc:198]
==============================================================================
Loading model
==============================================================================
I20240813 17:21:41.630676 130027 incremental_mapper.cc:225] Loading database
I20240813 17:21:41.631114 130027 database_cache.cc:65] Loading cameras...
I20240813 17:21:41.631135 130027 database_cache.cc:75]  8 in 0.000s
I20240813 17:21:41.631145 130027 database_cache.cc:83] Loading matches...
I20240813 17:21:41.631201 130027 database_cache.cc:89]  28 in 0.000s
I20240813 17:21:41.631209 130027 database_cache.cc:105] Loading images...
I20240813 17:21:41.632269 130027 database_cache.cc:155]  8 in 0.001s (connected 8)
I20240813 17:21:41.632282 130027 database_cache.cc:166] Building correspondence graph...
I20240813 17:21:41.633419 130027 database_cache.cc:195]  in 0.001s (ignored 0)
I20240813 17:21:41.633430 130027 timer.cc:91] Elapsed time: 0.000 [minutes]
I20240813 17:21:41.633692 130027 incremental_mapper.cc:546] Iterative triangulation
I20240813 17:21:41.633700 130027 incremental_mapper.cc:552] Triangulating image #8 (0)
I20240813 17:21:41.633706 130027 incremental_mapper.cc:554] => Image sees 0 / 506 points
I20240813 17:21:41.635299 130027 incremental_mapper.cc:552] Triangulating image #7 (1)
I20240813 17:21:41.635308 130027 incremental_mapper.cc:554] => Image sees 133 / 663 points
I20240813 17:21:41.635891 130027 incremental_mapper.cc:552] Triangulating image #6 (2)
I20240813 17:21:41.635900 130027 incremental_mapper.cc:554] => Image sees 156 / 565 points
I20240813 17:21:41.636588 130027 incremental_mapper.cc:552] Triangulating image #5 (3)
I20240813 17:21:41.636596 130027 incremental_mapper.cc:554] => Image sees 161 / 871 points
I20240813 17:21:41.639114 130027 incremental_mapper.cc:552] Triangulating image #4 (4)
I20240813 17:21:41.639122 130027 incremental_mapper.cc:554] => Image sees 285 / 1237 points
I20240813 17:21:41.642438 130027 incremental_mapper.cc:552] Triangulating image #3 (5)
I20240813 17:21:41.642447 130027 incremental_mapper.cc:554] => Image sees 599 / 1891 points
I20240813 17:21:41.644701 130027 incremental_mapper.cc:552] Triangulating image #2 (6)
I20240813 17:21:41.644708 130027 incremental_mapper.cc:554] => Image sees 760 / 2374 points
I20240813 17:21:41.645229 130027 incremental_mapper.cc:552] Triangulating image #1 (7)
I20240813 17:21:41.645236 130027 incremental_mapper.cc:554] => Image sees 790 / 2454 points
I20240813 17:21:41.645777 130027 incremental_mapper.cc:563] Retriangulation and Global bundle adjustment
I20240813 17:21:41.714931 130027 incremental_mapper.cc:572] Extracting colors
```
Given your error log, it looks like https://github.com/colmap/colmap/pull/2704 will solve the issue.

**Comment by sarlinpe** [comment] 2024-09-06 09:28
Likely fixed by https://github.com/colmap/colmap/pull/2704, please re-open this issue if not.

**Closed by sarlinpe** 2024-09-06 09:28 UTC
Labels: bug

**Comment by longyangqi** [comment] 2024-09-11 16:00
I get another error using the given data:

```
> colmap point_triangulator --database_path colmap_issue/database.db --image_path colmap_issue/images --input_path colmap_issue/ --output_path out
I0911 23:59:44.861191 137067 misc.cc:198] 
==============================================================================
Loading model
==============================================================================
I0911 23:59:45.195596 137067 incremental_mapper.cc:232] Loading database
I0911 23:59:45.337260 137067 database_cache.cc:65] Loading cameras...
I0911 23:59:45.351488 137067 database_cache.cc:75]  8 in 0.014s
I0911 23:59:45.351511 137067 database_cache.cc:83] Loading matches...
I0911 23:59:45.448124 137067 database_cache.cc:89]  28 in 0.097s
I0911 23:59:45.448146 137067 database_cache.cc:105] Loading images...
I0911 23:59:45.589874 137067 database_cache.cc:155]  8 in 0.142s (connected 8)
I0911 23:59:45.589903 137067 database_cache.cc:166] Building correspondence graph...
I0911 23:59:45.592072 137067 database_cache.cc:195]  in 0.002s (ignored 0)
I0911 23:59:45.592089 137067 timer.cc:91] Elapsed time: 0.004 [minutes]
I0911 23:59:45.615167 137067 incremental_mapper.cc:550] Iterative triangulation
I0911 23:59:45.615182 137067 incremental_mapper.cc:556] Triangulating image #8 (0)
I0911 23:59:45.615191 137067 incremental_mapper.cc:558] => Image sees 0 / 506 points
E0911 23:59:45.615206 137067 image.h:174] 'camera_ptr_' Must be non NULL
terminate called after throwing an instance of 'std::invalid_argument'
  what():  [image.h:174] 'camera_ptr_' Must be non NULL
*** Aborted at 1726070385 (unix time) try "date -d @1726070385" if you are using GNU date ***
PC: @     0x7fc5d60a500b gsignal
*** SIGABRT (@0x2176b) received by PID 137067 (TID 0x7fc5d1b0d000) from PID 137067; stack trace: ***
    @     0x7fc5d78ac631 (unknown)
    @     0x7fc5d7883420 (unknown)
    @     0x7fc5d60a500b gsignal
    @     0x7fc5d6084859 abort
    @     0x7fc5d645c8d1 (unknown)
    @     0x7fc5d646837c (unknown)
    @     0x7fc5d64683e7 std::terminate()
    @     0x7fc5d6468699 __cxa_throw
    @     0x55b4a9b54bb9 _ZN6colmap23IncrementalTriangulator16TriangulateImageERKNS0_7OptionsEj.cold
    @     0x55b4a9cec17a colmap::IncrementalMapper::TriangulateImage()
    @     0x55b4a9c77136 colmap::IncrementalPipeline::TriangulateReconstruction()
    @     0x55b4a9ba6624 colmap::RunPointTriangulatorImpl()
    @     0x55b4a9ba6c06 colmap::RunPointTriangulator()
    @     0x55b4a9b878f4 main
    @     0x7fc5d6086083 __libc_start_main
    @     0x55b4a9b8ea4e _start
Aborted (core dumped)
```

how can i fix it
Thanks!
